// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClassItems(arg1) {
  return window['go']['player']['Service']['AddClassItems'](arg1);
}

export function AddDomainCard(arg1, arg2, arg3) {
  return window['go']['player']['Service']['AddDomainCard'](arg1, arg2, arg3);
}

export function AdjustHope(arg1, arg2) {
  return window['go']['player']['Service']['AdjustHope'](arg1, arg2);
}

export function AdjustItemQty(arg1, arg2) {
  return window['go']['player']['Service']['AdjustItemQty'](arg1, arg2);
}

export function ApplyLevelUp(arg1) {
  return window['go']['player']['Service']['ApplyLevelUp'](arg1);
}

export function AvailableDomainCards(arg1) {
  return window['go']['player']['Service']['AvailableDomainCards'](arg1);
}

export function Beastforms(arg1) {
  return window['go']['player']['Service']['Beastforms'](arg1);
}

export function BrowseDomainCards(arg1) {
  return window['go']['player']['Service']['BrowseDomainCards'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['player']['Service']['DeleteCharacter'](arg1);
}

export function DeleteCompanion(arg1) {
  return window['go']['player']['Service']['DeleteCompanion'](arg1);
}

export function DeleteExperience(arg1) {
  return window['go']['player']['Service']['DeleteExperience'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['player']['Service']['DeleteItem'](arg1);
}

export function DomainList() {
  return window['go']['player']['Service']['DomainList']();
}

export function DropBeastform(arg1) {
  return window['go']['player']['Service']['DropBeastform'](arg1);
}

export function GetAncestry(arg1) {
  return window['go']['player']['Service']['GetAncestry'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['player']['Service']['GetCharacter'](arg1);
}

export function GetClass(arg1) {
  return window['go']['player']['Service']['GetClass'](arg1);
}

export function GetCommunity(arg1) {
  return window['go']['player']['Service']['GetCommunity'](arg1);
}

export function GetCompanion(arg1) {
  return window['go']['player']['Service']['GetCompanion'](arg1);
}

export function GetDomainCard(arg1) {
  return window['go']['player']['Service']['GetDomainCard'](arg1);
}

export function GetLoadout(arg1) {
  return window['go']['player']['Service']['GetLoadout'](arg1);
}

export function GetSheet(arg1) {
  return window['go']['player']['Service']['GetSheet'](arg1);
}

export function ItemKinds() {
  return window['go']['player']['Service']['ItemKinds']();
}

export function Limits() {
  return window['go']['player']['Service']['Limits']();
}

export function ListAncestries() {
  return window['go']['player']['Service']['ListAncestries']();
}

export function ListBeastforms(arg1) {
  return window['go']['player']['Service']['ListBeastforms'](arg1);
}

export function ListCharacters() {
  return window['go']['player']['Service']['ListCharacters']();
}

export function ListClasses() {
  return window['go']['player']['Service']['ListClasses']();
}

export function ListCommunities() {
  return window['go']['player']['Service']['ListCommunities']();
}

export function ListCompanions() {
  return window['go']['player']['Service']['ListCompanions']();
}

export function ListExperiences(arg1) {
  return window['go']['player']['Service']['ListExperiences'](arg1);
}

export function ListInventory(arg1) {
  return window['go']['player']['Service']['ListInventory'](arg1);
}

export function ListLevelUps(arg1) {
  return window['go']['player']['Service']['ListLevelUps'](arg1);
}

export function MarkArmor(arg1, arg2) {
  return window['go']['player']['Service']['MarkArmor'](arg1, arg2);
}

export function MarkCompanionStress(arg1, arg2) {
  return window['go']['player']['Service']['MarkCompanionStress'](arg1, arg2);
}

export function MarkHP(arg1, arg2) {
  return window['go']['player']['Service']['MarkHP'](arg1, arg2);
}

export function MarkStress(arg1, arg2) {
  return window['go']['player']['Service']['MarkStress'](arg1, arg2);
}

export function MoveDomainCard(arg1, arg2, arg3) {
  return window['go']['player']['Service']['MoveDomainCard'](arg1, arg2, arg3);
}

export function PlanLevelUp(arg1) {
  return window['go']['player']['Service']['PlanLevelUp'](arg1);
}

export function RemoveDomainCard(arg1, arg2) {
  return window['go']['player']['Service']['RemoveDomainCard'](arg1, arg2);
}

export function Rest(arg1) {
  return window['go']['player']['Service']['Rest'](arg1);
}

export function RestAllowance(arg1) {
  return window['go']['player']['Service']['RestAllowance'](arg1);
}

export function RestMoves(arg1) {
  return window['go']['player']['Service']['RestMoves'](arg1);
}

export function RollCompanionDamage(arg1, arg2, arg3) {
  return window['go']['player']['Service']['RollCompanionDamage'](arg1, arg2, arg3);
}

export function RollDamage(arg1, arg2, arg3, arg4) {
  return window['go']['player']['Service']['RollDamage'](arg1, arg2, arg3, arg4);
}

export function RollDuality(arg1) {
  return window['go']['player']['Service']['RollDuality'](arg1);
}

export function SaveCharacter(arg1) {
  return window['go']['player']['Service']['SaveCharacter'](arg1);
}

export function SaveCompanion(arg1) {
  return window['go']['player']['Service']['SaveCompanion'](arg1);
}

export function SaveExperience(arg1) {
  return window['go']['player']['Service']['SaveExperience'](arg1);
}

export function SaveItem(arg1) {
  return window['go']['player']['Service']['SaveItem'](arg1);
}

export function SetCompanionStress(arg1, arg2) {
  return window['go']['player']['Service']['SetCompanionStress'](arg1, arg2);
}

export function SetGold(arg1, arg2, arg3, arg4) {
  return window['go']['player']['Service']['SetGold'](arg1, arg2, arg3, arg4);
}

export function SetItemEquipped(arg1, arg2) {
  return window['go']['player']['Service']['SetItemEquipped'](arg1, arg2);
}

export function SetVitals(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['player']['Service']['SetVitals'](arg1, arg2, arg3, arg4, arg5);
}

export function SwapDomainCard(arg1) {
  return window['go']['player']['Service']['SwapDomainCard'](arg1);
}

export function TierForLevel(arg1) {
  return window['go']['player']['Service']['TierForLevel'](arg1);
}

export function ToggleCompanionUpgrade(arg1, arg2) {
  return window['go']['player']['Service']['ToggleCompanionUpgrade'](arg1, arg2);
}

export function Traits() {
  return window['go']['player']['Service']['Traits']();
}

export function Transform(arg1, arg2, arg3) {
  return window['go']['player']['Service']['Transform'](arg1, arg2, arg3);
}
