// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {player} from '../models';
import {cards} from '../models';

export function AddClassItems(arg1:number):Promise<Array<player.Item>>;

export function AddDomainCard(arg1:number,arg2:string,arg3:string):Promise<player.Loadout>;

export function AdjustHope(arg1:number,arg2:number):Promise<player.Character>;

export function AdjustItemQty(arg1:number,arg2:number):Promise<Array<player.Item>>;

export function ApplyLevelUp(arg1:player.LevelUpInput):Promise<player.Sheet>;

export function AvailableDomainCards(arg1:number):Promise<Array<cards.DomainCard>>;

export function Beastforms(arg1:number):Promise<player.BeastformView>;

export function BrowseDomainCards(arg1:player.DomainFilter):Promise<Array<cards.DomainCard>>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteCompanion(arg1:number):Promise<player.CompanionView>;

export function DeleteExperience(arg1:number):Promise<Array<player.Experience>>;

export function DeleteItem(arg1:number):Promise<Array<player.Item>>;

export function DomainList():Promise<Array<string>>;

export function DropBeastform(arg1:number):Promise<player.BeastformView>;

export function GetAncestry(arg1:string):Promise<cards.Ancestry>;

export function GetCharacter(arg1:number):Promise<player.Character>;

export function GetClass(arg1:string):Promise<cards.CharacterClass>;

export function GetCommunity(arg1:string):Promise<cards.Community>;

export function GetCompanion(arg1:number):Promise<player.CompanionView>;

export function GetDomainCard(arg1:string):Promise<cards.DomainCard>;

export function GetLoadout(arg1:number):Promise<player.Loadout>;

export function GetSheet(arg1:number):Promise<player.Sheet>;

export function ItemKinds():Promise<Array<string>>;

export function Limits():Promise<Record<string, number>>;

export function ListAncestries():Promise<Array<cards.Ancestry>>;

export function ListBeastforms(arg1:string):Promise<Array<cards.Beastform>>;

export function ListCharacters():Promise<Array<player.Character>>;

export function ListClasses():Promise<Array<cards.CharacterClass>>;

export function ListCommunities():Promise<Array<cards.Community>>;

export function ListCompanions():Promise<Array<cards.Companion>>;

export function ListExperiences(arg1:number):Promise<Array<player.Experience>>;

export function ListInventory(arg1:number):Promise<Array<player.Item>>;

export function ListLevelUps(arg1:number):Promise<Array<player.LevelUpRecord>>;

export function MarkArmor(arg1:number,arg2:number):Promise<player.Character>;

export function MarkCompanionStress(arg1:number,arg2:number):Promise<player.CompanionView>;

export function MarkHP(arg1:number,arg2:number):Promise<player.Character>;

export function MarkStress(arg1:number,arg2:number):Promise<player.Character>;

export function MoveDomainCard(arg1:number,arg2:string,arg3:string):Promise<player.Loadout>;

export function PlanLevelUp(arg1:number):Promise<player.LevelUpPlan>;

export function RemoveDomainCard(arg1:number,arg2:string):Promise<player.Loadout>;

export function Rest(arg1:player.RestInput):Promise<player.RestResult>;

export function RestAllowance(arg1:boolean):Promise<number>;

export function RestMoves(arg1:boolean):Promise<Array<player.RestMove>>;

export function RollCompanionDamage(arg1:number,arg2:number,arg3:boolean):Promise<player.DamageResult>;

export function RollDamage(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<player.DamageResult>;

export function RollDuality(arg1:player.RollRequest):Promise<player.Roll>;

export function SaveCharacter(arg1:player.CharacterInput):Promise<player.Character>;

export function SaveCompanion(arg1:player.CompanionInput):Promise<player.CompanionView>;

export function SaveExperience(arg1:player.ExperienceInput):Promise<Array<player.Experience>>;

export function SaveItem(arg1:player.ItemInput):Promise<Array<player.Item>>;

export function SetCompanionStress(arg1:number,arg2:number):Promise<player.CompanionView>;

export function SetGold(arg1:number,arg2:number,arg3:number,arg4:number):Promise<player.Character>;

export function SetItemEquipped(arg1:number,arg2:boolean):Promise<Array<player.Item>>;

export function SetVitals(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<player.Character>;

export function TierForLevel(arg1:number):Promise<number>;

export function ToggleCompanionUpgrade(arg1:number,arg2:string):Promise<player.CompanionView>;

export function Traits():Promise<Array<string>>;

export function Transform(arg1:number,arg2:string,arg3:boolean):Promise<player.BeastformView>;
