// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseAdversaries(arg1) {
  return window['go']['gm']['Service']['BrowseAdversaries'](arg1);
}

export function BrowseEnvironments(arg1) {
  return window['go']['gm']['Service']['BrowseEnvironments'](arg1);
}

export function ComputeBudget(arg1, arg2) {
  return window['go']['gm']['Service']['ComputeBudget'](arg1, arg2);
}

export function CreateCustomAdversary(arg1) {
  return window['go']['gm']['Service']['CreateCustomAdversary'](arg1);
}

export function CreateCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['CreateCustomEnvironment'](arg1);
}

export function CreateParty(arg1) {
  return window['go']['gm']['Service']['CreateParty'](arg1);
}

export function DeleteCustomAdversary(arg1) {
  return window['go']['gm']['Service']['DeleteCustomAdversary'](arg1);
}

export function DeleteCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['DeleteCustomEnvironment'](arg1);
}

export function DeleteEncounter(arg1) {
  return window['go']['gm']['Service']['DeleteEncounter'](arg1);
}

export function DeleteParty(arg1) {
  return window['go']['gm']['Service']['DeleteParty'](arg1);
}

export function GetAdversary(arg1) {
  return window['go']['gm']['Service']['GetAdversary'](arg1);
}

export function GetCustomAdversary(arg1) {
  return window['go']['gm']['Service']['GetCustomAdversary'](arg1);
}

export function GetCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['GetCustomEnvironment'](arg1);
}

export function GetEncounter(arg1) {
  return window['go']['gm']['Service']['GetEncounter'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['gm']['Service']['GetEnvironment'](arg1);
}

export function GetParty(arg1) {
  return window['go']['gm']['Service']['GetParty'](arg1);
}

export function ListCustomAdversaries(arg1) {
  return window['go']['gm']['Service']['ListCustomAdversaries'](arg1);
}

export function ListCustomEnvironments(arg1) {
  return window['go']['gm']['Service']['ListCustomEnvironments'](arg1);
}

export function ListEncounters() {
  return window['go']['gm']['Service']['ListEncounters']();
}

export function ListParties() {
  return window['go']['gm']['Service']['ListParties']();
}

export function SaveEncounter(arg1) {
  return window['go']['gm']['Service']['SaveEncounter'](arg1);
}

export function UpdateCustomAdversary(arg1) {
  return window['go']['gm']['Service']['UpdateCustomAdversary'](arg1);
}

export function UpdateCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['UpdateCustomEnvironment'](arg1);
}

export function UpdateParty(arg1, arg2) {
  return window['go']['gm']['Service']['UpdateParty'](arg1, arg2);
}
