// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustCampaignFear(arg1, arg2) {
  return window['go']['gm']['Service']['AdjustCampaignFear'](arg1, arg2);
}

export function AdjustFear(arg1, arg2) {
  return window['go']['gm']['Service']['AdjustFear'](arg1, arg2);
}

export function AdvanceCountdown(arg1, arg2) {
  return window['go']['gm']['Service']['AdvanceCountdown'](arg1, arg2);
}

export function BrowseAdversaries(arg1) {
  return window['go']['gm']['Service']['BrowseAdversaries'](arg1);
}

export function BrowseEnvironments(arg1) {
  return window['go']['gm']['Service']['BrowseEnvironments'](arg1);
}

export function ClearSpotlights(arg1) {
  return window['go']['gm']['Service']['ClearSpotlights'](arg1);
}

export function CombatsForSession(arg1) {
  return window['go']['gm']['Service']['CombatsForSession'](arg1);
}

export function ComputeBudget(arg1, arg2) {
  return window['go']['gm']['Service']['ComputeBudget'](arg1, arg2);
}

export function CreateCustomAdversary(arg1) {
  return window['go']['gm']['Service']['CreateCustomAdversary'](arg1);
}

export function CreateCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['CreateCustomEnvironment'](arg1);
}

export function CreateParty(arg1) {
  return window['go']['gm']['Service']['CreateParty'](arg1);
}

export function DeleteCampaign(arg1) {
  return window['go']['gm']['Service']['DeleteCampaign'](arg1);
}

export function DeleteCombat(arg1) {
  return window['go']['gm']['Service']['DeleteCombat'](arg1);
}

export function DeleteCountdown(arg1) {
  return window['go']['gm']['Service']['DeleteCountdown'](arg1);
}

export function DeleteCustomAdversary(arg1) {
  return window['go']['gm']['Service']['DeleteCustomAdversary'](arg1);
}

export function DeleteCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['DeleteCustomEnvironment'](arg1);
}

export function DeleteEncounter(arg1) {
  return window['go']['gm']['Service']['DeleteEncounter'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['gm']['Service']['DeleteNote'](arg1);
}

export function DeleteParty(arg1) {
  return window['go']['gm']['Service']['DeleteParty'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['gm']['Service']['DeleteSession'](arg1);
}

export function EndCombat(arg1) {
  return window['go']['gm']['Service']['EndCombat'](arg1);
}

export function GetActiveCombat() {
  return window['go']['gm']['Service']['GetActiveCombat']();
}

export function GetAdversary(arg1) {
  return window['go']['gm']['Service']['GetAdversary'](arg1);
}

export function GetCampaign(arg1) {
  return window['go']['gm']['Service']['GetCampaign'](arg1);
}

export function GetCombat(arg1) {
  return window['go']['gm']['Service']['GetCombat'](arg1);
}

export function GetCountdown(arg1) {
  return window['go']['gm']['Service']['GetCountdown'](arg1);
}

export function GetCustomAdversary(arg1) {
  return window['go']['gm']['Service']['GetCustomAdversary'](arg1);
}

export function GetCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['GetCustomEnvironment'](arg1);
}

export function GetEncounter(arg1) {
  return window['go']['gm']['Service']['GetEncounter'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['gm']['Service']['GetEnvironment'](arg1);
}

export function GetNote(arg1) {
  return window['go']['gm']['Service']['GetNote'](arg1);
}

export function GetParty(arg1) {
  return window['go']['gm']['Service']['GetParty'](arg1);
}

export function GetSession(arg1) {
  return window['go']['gm']['Service']['GetSession'](arg1);
}

export function LinkCombat(arg1, arg2, arg3) {
  return window['go']['gm']['Service']['LinkCombat'](arg1, arg2, arg3);
}

export function LinkEncounter(arg1, arg2) {
  return window['go']['gm']['Service']['LinkEncounter'](arg1, arg2);
}

export function ListCampaigns() {
  return window['go']['gm']['Service']['ListCampaigns']();
}

export function ListCombats() {
  return window['go']['gm']['Service']['ListCombats']();
}

export function ListCountdowns() {
  return window['go']['gm']['Service']['ListCountdowns']();
}

export function ListCountdownsForCampaign(arg1) {
  return window['go']['gm']['Service']['ListCountdownsForCampaign'](arg1);
}

export function ListCustomAdversaries(arg1) {
  return window['go']['gm']['Service']['ListCustomAdversaries'](arg1);
}

export function ListCustomEnvironments(arg1) {
  return window['go']['gm']['Service']['ListCustomEnvironments'](arg1);
}

export function ListEncounters() {
  return window['go']['gm']['Service']['ListEncounters']();
}

export function ListNotes(arg1) {
  return window['go']['gm']['Service']['ListNotes'](arg1);
}

export function ListNotesByKind(arg1, arg2) {
  return window['go']['gm']['Service']['ListNotesByKind'](arg1, arg2);
}

export function ListParties() {
  return window['go']['gm']['Service']['ListParties']();
}

export function ListSessions(arg1) {
  return window['go']['gm']['Service']['ListSessions'](arg1);
}

export function ListUnassignedCountdowns() {
  return window['go']['gm']['Service']['ListUnassignedCountdowns']();
}

export function MarkHP(arg1, arg2) {
  return window['go']['gm']['Service']['MarkHP'](arg1, arg2);
}

export function MarkStress(arg1, arg2) {
  return window['go']['gm']['Service']['MarkStress'](arg1, arg2);
}

export function NoteKinds() {
  return window['go']['gm']['Service']['NoteKinds']();
}

export function ReindexCards() {
  return window['go']['gm']['Service']['ReindexCards']();
}

export function RemoveCombatant(arg1) {
  return window['go']['gm']['Service']['RemoveCombatant'](arg1);
}

export function ResumeCombat(arg1) {
  return window['go']['gm']['Service']['ResumeCombat'](arg1);
}

export function SaveCampaign(arg1) {
  return window['go']['gm']['Service']['SaveCampaign'](arg1);
}

export function SaveCombatant(arg1) {
  return window['go']['gm']['Service']['SaveCombatant'](arg1);
}

export function SaveCountdown(arg1) {
  return window['go']['gm']['Service']['SaveCountdown'](arg1);
}

export function SaveEncounter(arg1) {
  return window['go']['gm']['Service']['SaveEncounter'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['gm']['Service']['SaveNote'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['gm']['Service']['SaveSession'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['gm']['Service']['Search'](arg1, arg2, arg3);
}

export function SessionsForEncounter(arg1) {
  return window['go']['gm']['Service']['SessionsForEncounter'](arg1);
}

export function SetCampaignFear(arg1, arg2) {
  return window['go']['gm']['Service']['SetCampaignFear'](arg1, arg2);
}

export function SetFear(arg1, arg2) {
  return window['go']['gm']['Service']['SetFear'](arg1, arg2);
}

export function SetSpotlight(arg1, arg2) {
  return window['go']['gm']['Service']['SetSpotlight'](arg1, arg2);
}

export function SetVitals(arg1, arg2, arg3) {
  return window['go']['gm']['Service']['SetVitals'](arg1, arg2, arg3);
}

export function StartCombat(arg1, arg2, arg3) {
  return window['go']['gm']['Service']['StartCombat'](arg1, arg2, arg3);
}

export function UnlinkEncounter(arg1, arg2) {
  return window['go']['gm']['Service']['UnlinkEncounter'](arg1, arg2);
}

export function UpdateCustomAdversary(arg1) {
  return window['go']['gm']['Service']['UpdateCustomAdversary'](arg1);
}

export function UpdateCustomEnvironment(arg1) {
  return window['go']['gm']['Service']['UpdateCustomEnvironment'](arg1);
}

export function UpdateParty(arg1, arg2) {
  return window['go']['gm']['Service']['UpdateParty'](arg1, arg2);
}
