// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gm} from '../models';
import {rules} from '../models';
import {cards} from '../models';

export function BrowseAdversaries(arg1:gm.Filter):Promise<Array<gm.BrowseAdversary>>;

export function BrowseEnvironments(arg1:gm.Filter):Promise<Array<gm.BrowseEnvironment>>;

export function ComputeBudget(arg1:rules.EncounterSettings,arg2:Array<rules.EncounterAdversary>):Promise<rules.BudgetSummary>;

export function CreateCustomAdversary(arg1:cards.Adversary):Promise<cards.Adversary>;

export function CreateCustomEnvironment(arg1:cards.Environment):Promise<cards.Environment>;

export function CreateParty(arg1:gm.PartyInput):Promise<gm.Party>;

export function DeleteCustomAdversary(arg1:string):Promise<void>;

export function DeleteCustomEnvironment(arg1:string):Promise<void>;

export function DeleteEncounter(arg1:number):Promise<void>;

export function DeleteParty(arg1:number):Promise<void>;

export function GetAdversary(arg1:string):Promise<gm.BrowseAdversary>;

export function GetCustomAdversary(arg1:string):Promise<cards.Adversary>;

export function GetCustomEnvironment(arg1:string):Promise<cards.Environment>;

export function GetEncounter(arg1:number):Promise<rules.EncounterView>;

export function GetEnvironment(arg1:string):Promise<gm.BrowseEnvironment>;

export function GetParty(arg1:number):Promise<gm.Party>;

export function ListCustomAdversaries(arg1:gm.Filter):Promise<Array<cards.Adversary>>;

export function ListCustomEnvironments(arg1:gm.Filter):Promise<Array<cards.Environment>>;

export function ListEncounters():Promise<Array<gm.EncounterSummary>>;

export function ListParties():Promise<Array<gm.Party>>;

export function SaveEncounter(arg1:gm.EncounterInput):Promise<rules.EncounterView>;

export function UpdateCustomAdversary(arg1:cards.Adversary):Promise<cards.Adversary>;

export function UpdateCustomEnvironment(arg1:cards.Environment):Promise<cards.Environment>;

export function UpdateParty(arg1:number,arg2:gm.PartyInput):Promise<gm.Party>;
