// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dice} from '../models';

export function Damage(arg1:number,arg2:number,arg3:number):Promise<dice.DamageRoll>;

export function Duality(arg1:boolean,arg2:boolean,arg3:number):Promise<dice.DualityDice>;

export function GM(arg1:boolean,arg2:boolean,arg3:number):Promise<dice.GMDice>;

export function Sizes():Promise<Array<number>>;
