// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Damage(arg1, arg2, arg3) {
  return window['go']['dice']['Roller']['Damage'](arg1, arg2, arg3);
}

export function Duality(arg1, arg2, arg3) {
  return window['go']['dice']['Roller']['Duality'](arg1, arg2, arg3);
}

export function GM(arg1, arg2, arg3) {
  return window['go']['dice']['Roller']['GM'](arg1, arg2, arg3);
}

export function Sizes() {
  return window['go']['dice']['Roller']['Sizes']();
}
