// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRole() {
  return window['go']['main']['App']['GetRole']();
}

export function SetRole(arg1) {
  return window['go']['main']['App']['SetRole'](arg1);
}
