// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRole():Promise<string>;

export function SetRole(arg1:string):Promise<void>;
