// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {main} from '../models';
import {gm} from '../models';

export function CheckForUpdate():Promise<update.Release>;

export function CurrentWindowSize():Promise<main.WindowSize>;

export function DataDirectory():Promise<string>;

export function ExportDatabase():Promise<string>;

export function ExportLibrary():Promise<string>;

export function GetUIScale():Promise<number>;

export function ImportDatabase():Promise<string>;

export function ImportLibrary():Promise<gm.ImportReport>;

export function OpenReleasesPage(arg1:string):Promise<void>;

export function SetUIScale(arg1:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<main.WindowSize>;

export function UIScales():Promise<Array<number>>;

export function Version():Promise<string>;

export function WindowPresets():Promise<Array<main.WindowSize>>;
