// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CurrentWindowSize() {
  return window['go']['main']['App']['CurrentWindowSize']();
}

export function DataDirectory() {
  return window['go']['main']['App']['DataDirectory']();
}

export function ExportDatabase() {
  return window['go']['main']['App']['ExportDatabase']();
}

export function ExportLibrary() {
  return window['go']['main']['App']['ExportLibrary']();
}

export function GetRole() {
  return window['go']['main']['App']['GetRole']();
}

export function GetUIScale() {
  return window['go']['main']['App']['GetUIScale']();
}

export function ImportDatabase() {
  return window['go']['main']['App']['ImportDatabase']();
}

export function ImportLibrary() {
  return window['go']['main']['App']['ImportLibrary']();
}

export function OpenReleasesPage(arg1) {
  return window['go']['main']['App']['OpenReleasesPage'](arg1);
}

export function SetRole(arg1) {
  return window['go']['main']['App']['SetRole'](arg1);
}

export function SetUIScale(arg1) {
  return window['go']['main']['App']['SetUIScale'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function UIScales() {
  return window['go']['main']['App']['UIScales']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WindowPresets() {
  return window['go']['main']['App']['WindowPresets']();
}
