// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentWindowSize() {
  return window['go']['main']['App']['CurrentWindowSize']();
}

export function GetRole() {
  return window['go']['main']['App']['GetRole']();
}

export function GetUIScale() {
  return window['go']['main']['App']['GetUIScale']();
}

export function SetRole(arg1) {
  return window['go']['main']['App']['SetRole'](arg1);
}

export function SetUIScale(arg1) {
  return window['go']['main']['App']['SetUIScale'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function UIScales() {
  return window['go']['main']['App']['UIScales']();
}

export function WindowPresets() {
  return window['go']['main']['App']['WindowPresets']();
}
