// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CurrentWindowSize():Promise<main.WindowSize>;

export function GetRole():Promise<string>;

export function GetUIScale():Promise<number>;

export function SetRole(arg1:string):Promise<void>;

export function SetUIScale(arg1:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<main.WindowSize>;

export function UIScales():Promise<Array<number>>;

export function WindowPresets():Promise<Array<main.WindowSize>>;
