// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"
)

const adjustCampaignFear = `-- name: AdjustCampaignFear :one
UPDATE campaigns SET
  current_fear = max(0, min(12, current_fear + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, description, current_fear, created_at, updated_at, master_note, master_note_updated_at
`

type AdjustCampaignFearParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCampaignFear(ctx context.Context, arg AdjustCampaignFearParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, adjustCampaignFear, arg.Delta, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrentFear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MasterNote,
		&i.MasterNoteUpdatedAt,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, description)
VALUES (?,?)
RETURNING id, name, description, current_fear, created_at, updated_at, master_note, master_note_updated_at
`

type CreateCampaignParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign, arg.Name, arg.Description)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrentFear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MasterNote,
		&i.MasterNoteUpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = ?
`

func (q *Queries) DeleteCampaign(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, id)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, description, current_fear, created_at, updated_at, master_note, master_note_updated_at FROM campaigns
WHERE id = ?
`

func (q *Queries) GetCampaign(ctx context.Context, id int64) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrentFear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MasterNote,
		&i.MasterNoteUpdatedAt,
	)
	return i, err
}

const getCampaignMasterNote = `-- name: GetCampaignMasterNote :one
SELECT master_note, master_note_updated_at FROM campaigns
WHERE id = ?
`

type GetCampaignMasterNoteRow struct {
	MasterNote          string
	MasterNoteUpdatedAt string
}

func (q *Queries) GetCampaignMasterNote(ctx context.Context, id int64) (GetCampaignMasterNoteRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaignMasterNote, id)
	var i GetCampaignMasterNoteRow
	err := row.Scan(&i.MasterNote, &i.MasterNoteUpdatedAt)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, description, current_fear, created_at, updated_at, master_note, master_note_updated_at FROM campaigns
ORDER BY updated_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CurrentFear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MasterNote,
			&i.MasterNoteUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCampaignFear = `-- name: SetCampaignFear :one
UPDATE campaigns SET
  current_fear = max(0, min(12, CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, description, current_fear, created_at, updated_at, master_note, master_note_updated_at
`

type SetCampaignFearParams struct {
	Fear int64
	ID   int64
}

func (q *Queries) SetCampaignFear(ctx context.Context, arg SetCampaignFearParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, setCampaignFear, arg.Fear, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrentFear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MasterNote,
		&i.MasterNoteUpdatedAt,
	)
	return i, err
}

const setCampaignMasterNote = `-- name: SetCampaignMasterNote :one
UPDATE campaigns SET
  master_note = ?1,
  master_note_updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING master_note, master_note_updated_at
`

type SetCampaignMasterNoteParams struct {
	MasterNote string
	ID         int64
}

type SetCampaignMasterNoteRow struct {
	MasterNote          string
	MasterNoteUpdatedAt string
}

func (q *Queries) SetCampaignMasterNote(ctx context.Context, arg SetCampaignMasterNoteParams) (SetCampaignMasterNoteRow, error) {
	row := q.db.QueryRowContext(ctx, setCampaignMasterNote, arg.MasterNote, arg.ID)
	var i SetCampaignMasterNoteRow
	err := row.Scan(&i.MasterNote, &i.MasterNoteUpdatedAt)
	return i, err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
  name = ?,
  description = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, name, description, current_fear, created_at, updated_at, master_note, master_note_updated_at
`

type UpdateCampaignParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign, arg.Name, arg.Description, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrentFear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MasterNote,
		&i.MasterNoteUpdatedAt,
	)
	return i, err
}
