// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package db

import (
	"context"
)

const adjustCharacterArmor = `-- name: AdjustCharacterArmor :one
UPDATE characters SET
  armor_marked = max(0, min(armor_score, armor_marked + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type AdjustCharacterArmorParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCharacterArmor(ctx context.Context, arg AdjustCharacterArmorParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, adjustCharacterArmor, arg.Delta, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const adjustCharacterHP = `-- name: AdjustCharacterHP :one
UPDATE characters SET
  hp_marked = max(0, min(hp_max, hp_marked + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type AdjustCharacterHPParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCharacterHP(ctx context.Context, arg AdjustCharacterHPParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, adjustCharacterHP, arg.Delta, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const adjustCharacterHope = `-- name: AdjustCharacterHope :one
UPDATE characters SET
  hope = max(0, min(6, hope + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type AdjustCharacterHopeParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCharacterHope(ctx context.Context, arg AdjustCharacterHopeParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, adjustCharacterHope, arg.Delta, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const adjustCharacterStress = `-- name: AdjustCharacterStress :one
UPDATE characters SET
  stress_marked = max(0, min(stress_max, stress_marked + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type AdjustCharacterStressParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCharacterStress(ctx context.Context, arg AdjustCharacterStressParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, adjustCharacterStress, arg.Delta, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
  name, pronouns, class_slug, subclass_slug, ancestry_slug, community_slug,
  agility, strength, finesse, instinct, presence, knowledge,
  hp_max, stress_max, hope, evasion, armor_score,
  threshold_major, threshold_severe, background, connections
)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type CreateCharacterParams struct {
	Name            string
	Pronouns        string
	ClassSlug       string
	SubclassSlug    string
	AncestrySlug    string
	CommunitySlug   string
	Agility         int64
	Strength        int64
	Finesse         int64
	Instinct        int64
	Presence        int64
	Knowledge       int64
	HpMax           int64
	StressMax       int64
	Hope            int64
	Evasion         int64
	ArmorScore      int64
	ThresholdMajor  int64
	ThresholdSevere int64
	Background      string
	Connections     string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.Name,
		arg.Pronouns,
		arg.ClassSlug,
		arg.SubclassSlug,
		arg.AncestrySlug,
		arg.CommunitySlug,
		arg.Agility,
		arg.Strength,
		arg.Finesse,
		arg.Instinct,
		arg.Presence,
		arg.Knowledge,
		arg.HpMax,
		arg.StressMax,
		arg.Hope,
		arg.Evasion,
		arg.ArmorScore,
		arg.ThresholdMajor,
		arg.ThresholdSevere,
		arg.Background,
		arg.Connections,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = ?
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug FROM characters
WHERE id = ?
`

func (q *Queries) GetCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug FROM characters
ORDER BY updated_at DESC
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pronouns,
			&i.ClassSlug,
			&i.SubclassSlug,
			&i.SubclassMastery,
			&i.MulticlassSlug,
			&i.MulticlassSubclassSlug,
			&i.AncestrySlug,
			&i.CommunitySlug,
			&i.Level,
			&i.Proficiency,
			&i.Agility,
			&i.Strength,
			&i.Finesse,
			&i.Instinct,
			&i.Presence,
			&i.Knowledge,
			&i.MarkedTraits,
			&i.HpMax,
			&i.HpMarked,
			&i.StressMax,
			&i.StressMarked,
			&i.Hope,
			&i.Evasion,
			&i.ArmorScore,
			&i.ArmorMarked,
			&i.ThresholdMajor,
			&i.ThresholdSevere,
			&i.GoldHandfuls,
			&i.GoldBags,
			&i.GoldChests,
			&i.Background,
			&i.Connections,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BeastformSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterBeastform = `-- name: SetCharacterBeastform :one
UPDATE characters SET
  beastform_slug = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type SetCharacterBeastformParams struct {
	BeastformSlug string
	ID            int64
}

func (q *Queries) SetCharacterBeastform(ctx context.Context, arg SetCharacterBeastformParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, setCharacterBeastform, arg.BeastformSlug, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const setCharacterGold = `-- name: SetCharacterGold :one
UPDATE characters SET
  gold_handfuls = max(0, min(9, CAST(?1 AS INTEGER))),
  gold_bags = max(0, min(9, CAST(?2 AS INTEGER))),
  gold_chests = max(0, min(99, CAST(?3 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?4
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type SetCharacterGoldParams struct {
	GoldHandfuls int64
	GoldBags     int64
	GoldChests   int64
	ID           int64
}

func (q *Queries) SetCharacterGold(ctx context.Context, arg SetCharacterGoldParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, setCharacterGold,
		arg.GoldHandfuls,
		arg.GoldBags,
		arg.GoldChests,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const setCharacterVitals = `-- name: SetCharacterVitals :one
UPDATE characters SET
  hp_marked = max(0, min(hp_max, CAST(?1 AS INTEGER))),
  stress_marked = max(0, min(stress_max, CAST(?2 AS INTEGER))),
  hope = max(0, min(6, CAST(?3 AS INTEGER))),
  armor_marked = max(0, min(armor_score, CAST(?4 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?5
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type SetCharacterVitalsParams struct {
	HpMarked     int64
	StressMarked int64
	Hope         int64
	ArmorMarked  int64
	ID           int64
}

func (q *Queries) SetCharacterVitals(ctx context.Context, arg SetCharacterVitalsParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, setCharacterVitals,
		arg.HpMarked,
		arg.StressMarked,
		arg.Hope,
		arg.ArmorMarked,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters SET
  name = ?1,
  pronouns = ?2,
  class_slug = ?3,
  subclass_slug = ?4,
  ancestry_slug = ?5,
  community_slug = ?6,
  agility = ?7,
  strength = ?8,
  finesse = ?9,
  instinct = ?10,
  presence = ?11,
  knowledge = ?12,
  hp_max = ?13,
  hp_marked = min(hp_marked, ?13),
  stress_max = ?14,
  stress_marked = min(stress_marked, ?14),
  evasion = ?15,
  armor_score = ?16,
  armor_marked = min(armor_marked, ?16),
  threshold_major = ?17,
  threshold_severe = ?18,
  background = ?19,
  connections = ?20,
  notes = ?21,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?22
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type UpdateCharacterParams struct {
	Name            string
	Pronouns        string
	ClassSlug       string
	SubclassSlug    string
	AncestrySlug    string
	CommunitySlug   string
	Agility         int64
	Strength        int64
	Finesse         int64
	Instinct        int64
	Presence        int64
	Knowledge       int64
	HpMax           int64
	StressMax       int64
	Evasion         int64
	ArmorScore      int64
	ThresholdMajor  int64
	ThresholdSevere int64
	Background      string
	Connections     string
	Notes           string
	ID              int64
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacter,
		arg.Name,
		arg.Pronouns,
		arg.ClassSlug,
		arg.SubclassSlug,
		arg.AncestrySlug,
		arg.CommunitySlug,
		arg.Agility,
		arg.Strength,
		arg.Finesse,
		arg.Instinct,
		arg.Presence,
		arg.Knowledge,
		arg.HpMax,
		arg.StressMax,
		arg.Evasion,
		arg.ArmorScore,
		arg.ThresholdMajor,
		arg.ThresholdSevere,
		arg.Background,
		arg.Connections,
		arg.Notes,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}

const updateCharacterProgress = `-- name: UpdateCharacterProgress :one
UPDATE characters SET
  level = ?1,
  proficiency = ?2,
  subclass_mastery = ?3,
  multiclass_slug = ?4,
  multiclass_subclass_slug = ?5,
  agility = ?6,
  strength = ?7,
  finesse = ?8,
  instinct = ?9,
  presence = ?10,
  knowledge = ?11,
  marked_traits = ?12,
  hp_max = ?13,
  stress_max = ?14,
  evasion = ?15,
  threshold_major = ?16,
  threshold_severe = ?17,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?18
RETURNING id, name, pronouns, class_slug, subclass_slug, subclass_mastery, multiclass_slug, multiclass_subclass_slug, ancestry_slug, community_slug, level, proficiency, agility, strength, finesse, instinct, presence, knowledge, marked_traits, hp_max, hp_marked, stress_max, stress_marked, hope, evasion, armor_score, armor_marked, threshold_major, threshold_severe, gold_handfuls, gold_bags, gold_chests, background, connections, notes, created_at, updated_at, beastform_slug
`

type UpdateCharacterProgressParams struct {
	Level                  int64
	Proficiency            int64
	SubclassMastery        int64
	MulticlassSlug         string
	MulticlassSubclassSlug string
	Agility                int64
	Strength               int64
	Finesse                int64
	Instinct               int64
	Presence               int64
	Knowledge              int64
	MarkedTraits           string
	HpMax                  int64
	StressMax              int64
	Evasion                int64
	ThresholdMajor         int64
	ThresholdSevere        int64
	ID                     int64
}

func (q *Queries) UpdateCharacterProgress(ctx context.Context, arg UpdateCharacterProgressParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterProgress,
		arg.Level,
		arg.Proficiency,
		arg.SubclassMastery,
		arg.MulticlassSlug,
		arg.MulticlassSubclassSlug,
		arg.Agility,
		arg.Strength,
		arg.Finesse,
		arg.Instinct,
		arg.Presence,
		arg.Knowledge,
		arg.MarkedTraits,
		arg.HpMax,
		arg.StressMax,
		arg.Evasion,
		arg.ThresholdMajor,
		arg.ThresholdSevere,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pronouns,
		&i.ClassSlug,
		&i.SubclassSlug,
		&i.SubclassMastery,
		&i.MulticlassSlug,
		&i.MulticlassSubclassSlug,
		&i.AncestrySlug,
		&i.CommunitySlug,
		&i.Level,
		&i.Proficiency,
		&i.Agility,
		&i.Strength,
		&i.Finesse,
		&i.Instinct,
		&i.Presence,
		&i.Knowledge,
		&i.MarkedTraits,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Hope,
		&i.Evasion,
		&i.ArmorScore,
		&i.ArmorMarked,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.GoldHandfuls,
		&i.GoldBags,
		&i.GoldChests,
		&i.Background,
		&i.Connections,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BeastformSlug,
	)
	return i, err
}
