// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: character_levelups.sql

package db

import (
	"context"
)

const createLevelUp = `-- name: CreateLevelUp :one
INSERT INTO character_levelups (character_id, level, tier, choices, summary)
VALUES (?,?,?,?,?)
RETURNING id, character_id, level, tier, choices, summary, created_at
`

type CreateLevelUpParams struct {
	CharacterID int64
	Level       int64
	Tier        int64
	Choices     string
	Summary     string
}

func (q *Queries) CreateLevelUp(ctx context.Context, arg CreateLevelUpParams) (CharacterLevelup, error) {
	row := q.db.QueryRowContext(ctx, createLevelUp,
		arg.CharacterID,
		arg.Level,
		arg.Tier,
		arg.Choices,
		arg.Summary,
	)
	var i CharacterLevelup
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Level,
		&i.Tier,
		&i.Choices,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listLevelUps = `-- name: ListLevelUps :many
SELECT id, character_id, level, tier, choices, summary, created_at FROM character_levelups
WHERE character_id = ?
ORDER BY level ASC
`

func (q *Queries) ListLevelUps(ctx context.Context, characterID int64) ([]CharacterLevelup, error) {
	rows, err := q.db.QueryContext(ctx, listLevelUps, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterLevelup
	for rows.Next() {
		var i CharacterLevelup
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Level,
			&i.Tier,
			&i.Choices,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevelUpsForTier = `-- name: ListLevelUpsForTier :many
SELECT id, character_id, level, tier, choices, summary, created_at FROM character_levelups
WHERE character_id = ? AND tier = ?
ORDER BY level ASC
`

type ListLevelUpsForTierParams struct {
	CharacterID int64
	Tier        int64
}

func (q *Queries) ListLevelUpsForTier(ctx context.Context, arg ListLevelUpsForTierParams) ([]CharacterLevelup, error) {
	rows, err := q.db.QueryContext(ctx, listLevelUpsForTier, arg.CharacterID, arg.Tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterLevelup
	for rows.Next() {
		var i CharacterLevelup
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Level,
			&i.Tier,
			&i.Choices,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
