// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: character_domain_cards.sql

package db

import (
	"context"
)

const addCharacterDomainCard = `-- name: AddCharacterDomainCard :one
INSERT INTO character_domain_cards (character_id, card_slug, location)
VALUES (?,?,?)
RETURNING id, character_id, card_slug, location, created_at, updated_at
`

type AddCharacterDomainCardParams struct {
	CharacterID int64
	CardSlug    string
	Location    string
}

func (q *Queries) AddCharacterDomainCard(ctx context.Context, arg AddCharacterDomainCardParams) (CharacterDomainCard, error) {
	row := q.db.QueryRowContext(ctx, addCharacterDomainCard, arg.CharacterID, arg.CardSlug, arg.Location)
	var i CharacterDomainCard
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.CardSlug,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCharacterLoadout = `-- name: CountCharacterLoadout :one
SELECT count(*) FROM character_domain_cards
WHERE character_id = ? AND location = 'loadout'
`

func (q *Queries) CountCharacterLoadout(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCharacterLoadout, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCharacterDomainCard = `-- name: GetCharacterDomainCard :one
SELECT id, character_id, card_slug, location, created_at, updated_at FROM character_domain_cards
WHERE character_id = ? AND card_slug = ?
`

type GetCharacterDomainCardParams struct {
	CharacterID int64
	CardSlug    string
}

func (q *Queries) GetCharacterDomainCard(ctx context.Context, arg GetCharacterDomainCardParams) (CharacterDomainCard, error) {
	row := q.db.QueryRowContext(ctx, getCharacterDomainCard, arg.CharacterID, arg.CardSlug)
	var i CharacterDomainCard
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.CardSlug,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacterDomainCards = `-- name: ListCharacterDomainCards :many
SELECT id, character_id, card_slug, location, created_at, updated_at FROM character_domain_cards
WHERE character_id = ?
ORDER BY id ASC
`

func (q *Queries) ListCharacterDomainCards(ctx context.Context, characterID int64) ([]CharacterDomainCard, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterDomainCards, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterDomainCard
	for rows.Next() {
		var i CharacterDomainCard
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.CardSlug,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCharacterDomainCard = `-- name: RemoveCharacterDomainCard :exec
DELETE FROM character_domain_cards
WHERE character_id = ? AND card_slug = ?
`

type RemoveCharacterDomainCardParams struct {
	CharacterID int64
	CardSlug    string
}

func (q *Queries) RemoveCharacterDomainCard(ctx context.Context, arg RemoveCharacterDomainCardParams) error {
	_, err := q.db.ExecContext(ctx, removeCharacterDomainCard, arg.CharacterID, arg.CardSlug)
	return err
}

const setDomainCardLocation = `-- name: SetDomainCardLocation :one
UPDATE character_domain_cards SET
  location = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE character_id = ?2 AND card_slug = ?3
RETURNING id, character_id, card_slug, location, created_at, updated_at
`

type SetDomainCardLocationParams struct {
	Location    string
	CharacterID int64
	CardSlug    string
}

func (q *Queries) SetDomainCardLocation(ctx context.Context, arg SetDomainCardLocationParams) (CharacterDomainCard, error) {
	row := q.db.QueryRowContext(ctx, setDomainCardLocation, arg.Location, arg.CharacterID, arg.CardSlug)
	var i CharacterDomainCard
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.CardSlug,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
