// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: combatants.sql

package db

import (
	"context"
	"database/sql"
)

const adjustCombatantHP = `-- name: AdjustCombatantHP :one
UPDATE combatants SET
  hp_marked = max(0, min(hp_max, hp_marked + ?1)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at
`

type AdjustCombatantHPParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCombatantHP(ctx context.Context, arg AdjustCombatantHPParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, adjustCombatantHP, arg.Delta, arg.ID)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adjustCombatantStress = `-- name: AdjustCombatantStress :one
UPDATE combatants SET
  stress_marked = max(0, min(stress_max, stress_marked + ?1)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at
`

type AdjustCombatantStressParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCombatantStress(ctx context.Context, arg AdjustCombatantStressParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, adjustCombatantStress, arg.Delta, arg.ID)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCombatantSpotlights = `-- name: ClearCombatantSpotlights :exec
UPDATE combatants SET
  spotlight = 0,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE combat_id = ? AND spotlight = 1
`

func (q *Queries) ClearCombatantSpotlights(ctx context.Context, combatID int64) error {
	_, err := q.db.ExecContext(ctx, clearCombatantSpotlights, combatID)
	return err
}

const createCombatant = `-- name: CreateCombatant :one
INSERT INTO combatants (
  combat_id, adversary_slug, display_name, hp_max, stress_max
)
VALUES (?,?,?,?,?)
RETURNING id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at
`

type CreateCombatantParams struct {
	CombatID      int64
	AdversarySlug sql.NullString
	DisplayName   string
	HpMax         int64
	StressMax     int64
}

func (q *Queries) CreateCombatant(ctx context.Context, arg CreateCombatantParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, createCombatant,
		arg.CombatID,
		arg.AdversarySlug,
		arg.DisplayName,
		arg.HpMax,
		arg.StressMax,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCombatant = `-- name: DeleteCombatant :exec
DELETE FROM combatants
WHERE id = ?
`

func (q *Queries) DeleteCombatant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCombatant, id)
	return err
}

const deleteCombatantsForCombat = `-- name: DeleteCombatantsForCombat :exec
DELETE FROM combatants
WHERE combat_id = ?
`

func (q *Queries) DeleteCombatantsForCombat(ctx context.Context, combatID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCombatantsForCombat, combatID)
	return err
}

const getCombatant = `-- name: GetCombatant :one
SELECT id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at FROM combatants
WHERE id = ?
`

func (q *Queries) GetCombatant(ctx context.Context, id int64) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, getCombatant, id)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCombatants = `-- name: ListCombatants :many
SELECT id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at FROM combatants
WHERE combat_id = ?
ORDER BY id ASC
`

func (q *Queries) ListCombatants(ctx context.Context, combatID int64) ([]Combatant, error) {
	rows, err := q.db.QueryContext(ctx, listCombatants, combatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Combatant
	for rows.Next() {
		var i Combatant
		if err := rows.Scan(
			&i.ID,
			&i.CombatID,
			&i.AdversarySlug,
			&i.DisplayName,
			&i.HpMax,
			&i.HpMarked,
			&i.StressMax,
			&i.StressMarked,
			&i.Spotlight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCombatantSpotlight = `-- name: SetCombatantSpotlight :one
UPDATE combatants SET
  spotlight = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at
`

type SetCombatantSpotlightParams struct {
	Spotlight int64
	ID        int64
}

func (q *Queries) SetCombatantSpotlight(ctx context.Context, arg SetCombatantSpotlightParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, setCombatantSpotlight, arg.Spotlight, arg.ID)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCombatantVitals = `-- name: SetCombatantVitals :one
UPDATE combatants SET
  hp_marked = max(0, min(hp_max, ?1)),
  stress_marked = max(0, min(stress_max, ?2)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?3
RETURNING id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at
`

type SetCombatantVitalsParams struct {
	HpMarked     interface{}
	StressMarked interface{}
	ID           int64
}

func (q *Queries) SetCombatantVitals(ctx context.Context, arg SetCombatantVitalsParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, setCombatantVitals, arg.HpMarked, arg.StressMarked, arg.ID)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatant = `-- name: UpdateCombatant :one
UPDATE combatants SET
  display_name = ?1,
  hp_max = ?2,
  stress_max = ?3,
  hp_marked = min(hp_marked, ?2),
  stress_marked = min(stress_marked, ?3),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?4
RETURNING id, combat_id, adversary_slug, display_name, hp_max, hp_marked, stress_max, stress_marked, spotlight, created_at, updated_at
`

type UpdateCombatantParams struct {
	DisplayName string
	HpMax       int64
	StressMax   int64
	ID          int64
}

func (q *Queries) UpdateCombatant(ctx context.Context, arg UpdateCombatantParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatant,
		arg.DisplayName,
		arg.HpMax,
		arg.StressMax,
		arg.ID,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.CombatID,
		&i.AdversarySlug,
		&i.DisplayName,
		&i.HpMax,
		&i.HpMarked,
		&i.StressMax,
		&i.StressMarked,
		&i.Spotlight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
