// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: combats.sql

package db

import (
	"context"
	"database/sql"
)

const adjustFear = `-- name: AdjustFear :one
UPDATE combats SET
  fear = max(0, min(12, fear + ?1)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, encounter_id, fear, active, created_at, updated_at
`

type AdjustFearParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustFear(ctx context.Context, arg AdjustFearParams) (Combat, error) {
	row := q.db.QueryRowContext(ctx, adjustFear, arg.Delta, arg.ID)
	var i Combat
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Fear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCombat = `-- name: CreateCombat :one
INSERT INTO combats (encounter_id)
VALUES (?)
RETURNING id, encounter_id, fear, active, created_at, updated_at
`

func (q *Queries) CreateCombat(ctx context.Context, encounterID sql.NullInt64) (Combat, error) {
	row := q.db.QueryRowContext(ctx, createCombat, encounterID)
	var i Combat
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Fear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAllCombats = `-- name: DeactivateAllCombats :exec
UPDATE combats SET
  active = 0,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE active = 1
`

func (q *Queries) DeactivateAllCombats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllCombats)
	return err
}

const deleteCombat = `-- name: DeleteCombat :exec
DELETE FROM combats
WHERE id = ?
`

func (q *Queries) DeleteCombat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCombat, id)
	return err
}

const getActiveCombat = `-- name: GetActiveCombat :one
SELECT id, encounter_id, fear, active, created_at, updated_at FROM combats
WHERE active = 1
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCombat(ctx context.Context) (Combat, error) {
	row := q.db.QueryRowContext(ctx, getActiveCombat)
	var i Combat
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Fear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCombat = `-- name: GetCombat :one
SELECT id, encounter_id, fear, active, created_at, updated_at FROM combats
WHERE id = ?
`

func (q *Queries) GetCombat(ctx context.Context, id int64) (Combat, error) {
	row := q.db.QueryRowContext(ctx, getCombat, id)
	var i Combat
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Fear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCombats = `-- name: ListCombats :many
SELECT id, encounter_id, fear, active, created_at, updated_at FROM combats
ORDER BY created_at DESC
`

func (q *Queries) ListCombats(ctx context.Context) ([]Combat, error) {
	rows, err := q.db.QueryContext(ctx, listCombats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Combat
	for rows.Next() {
		var i Combat
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.Fear,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatsForEncounter = `-- name: ListCombatsForEncounter :many
SELECT id, encounter_id, fear, active, created_at, updated_at FROM combats
WHERE encounter_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListCombatsForEncounter(ctx context.Context, encounterID sql.NullInt64) ([]Combat, error) {
	rows, err := q.db.QueryContext(ctx, listCombatsForEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Combat
	for rows.Next() {
		var i Combat
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.Fear,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCombatActive = `-- name: SetCombatActive :one
UPDATE combats SET
  active = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, encounter_id, fear, active, created_at, updated_at
`

type SetCombatActiveParams struct {
	Active int64
	ID     int64
}

func (q *Queries) SetCombatActive(ctx context.Context, arg SetCombatActiveParams) (Combat, error) {
	row := q.db.QueryRowContext(ctx, setCombatActive, arg.Active, arg.ID)
	var i Combat
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Fear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setFear = `-- name: SetFear :one
UPDATE combats SET
  fear = max(0, min(12, ?1)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, encounter_id, fear, active, created_at, updated_at
`

type SetFearParams struct {
	Fear interface{}
	ID   int64
}

func (q *Queries) SetFear(ctx context.Context, arg SetFearParams) (Combat, error) {
	row := q.db.QueryRowContext(ctx, setFear, arg.Fear, arg.ID)
	var i Combat
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Fear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
