// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companions.sql

package db

import (
	"context"
)

const adjustCompanionStress = `-- name: AdjustCompanionStress :one
UPDATE companions SET
  stress_marked = max(0, min(stress_max, stress_marked + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE character_id = ?2
RETURNING id, character_id, name, evasion, damage_die, attack_range, attack, stress_max, stress_marked, experiences, upgrades, notes, created_at, updated_at
`

type AdjustCompanionStressParams struct {
	Delta       int64
	CharacterID int64
}

func (q *Queries) AdjustCompanionStress(ctx context.Context, arg AdjustCompanionStressParams) (Companion, error) {
	row := q.db.QueryRowContext(ctx, adjustCompanionStress, arg.Delta, arg.CharacterID)
	var i Companion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Evasion,
		&i.DamageDie,
		&i.AttackRange,
		&i.Attack,
		&i.StressMax,
		&i.StressMarked,
		&i.Experiences,
		&i.Upgrades,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompanion = `-- name: CreateCompanion :one
INSERT INTO companions (
  character_id, name, evasion, damage_die, attack_range, attack,
  stress_max, experiences, upgrades, notes
)
VALUES (?,?,?,?,?,?,?,?,?,?)
RETURNING id, character_id, name, evasion, damage_die, attack_range, attack, stress_max, stress_marked, experiences, upgrades, notes, created_at, updated_at
`

type CreateCompanionParams struct {
	CharacterID int64
	Name        string
	Evasion     int64
	DamageDie   string
	AttackRange string
	Attack      string
	StressMax   int64
	Experiences string
	Upgrades    string
	Notes       string
}

func (q *Queries) CreateCompanion(ctx context.Context, arg CreateCompanionParams) (Companion, error) {
	row := q.db.QueryRowContext(ctx, createCompanion,
		arg.CharacterID,
		arg.Name,
		arg.Evasion,
		arg.DamageDie,
		arg.AttackRange,
		arg.Attack,
		arg.StressMax,
		arg.Experiences,
		arg.Upgrades,
		arg.Notes,
	)
	var i Companion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Evasion,
		&i.DamageDie,
		&i.AttackRange,
		&i.Attack,
		&i.StressMax,
		&i.StressMarked,
		&i.Experiences,
		&i.Upgrades,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompanion = `-- name: DeleteCompanion :exec
DELETE FROM companions
WHERE character_id = ?
`

func (q *Queries) DeleteCompanion(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompanion, characterID)
	return err
}

const getCompanion = `-- name: GetCompanion :one
SELECT id, character_id, name, evasion, damage_die, attack_range, attack, stress_max, stress_marked, experiences, upgrades, notes, created_at, updated_at FROM companions
WHERE character_id = ?
`

func (q *Queries) GetCompanion(ctx context.Context, characterID int64) (Companion, error) {
	row := q.db.QueryRowContext(ctx, getCompanion, characterID)
	var i Companion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Evasion,
		&i.DamageDie,
		&i.AttackRange,
		&i.Attack,
		&i.StressMax,
		&i.StressMarked,
		&i.Experiences,
		&i.Upgrades,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCompanionStress = `-- name: SetCompanionStress :one
UPDATE companions SET
  stress_marked = max(0, min(stress_max, CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE character_id = ?2
RETURNING id, character_id, name, evasion, damage_die, attack_range, attack, stress_max, stress_marked, experiences, upgrades, notes, created_at, updated_at
`

type SetCompanionStressParams struct {
	StressMarked int64
	CharacterID  int64
}

func (q *Queries) SetCompanionStress(ctx context.Context, arg SetCompanionStressParams) (Companion, error) {
	row := q.db.QueryRowContext(ctx, setCompanionStress, arg.StressMarked, arg.CharacterID)
	var i Companion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Evasion,
		&i.DamageDie,
		&i.AttackRange,
		&i.Attack,
		&i.StressMax,
		&i.StressMarked,
		&i.Experiences,
		&i.Upgrades,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompanion = `-- name: UpdateCompanion :one
UPDATE companions SET
  name = ?1,
  evasion = ?2,
  damage_die = ?3,
  attack_range = ?4,
  attack = ?5,
  stress_max = ?6,
  stress_marked = min(stress_marked, ?6),
  experiences = ?7,
  upgrades = ?8,
  notes = ?9,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE character_id = ?10
RETURNING id, character_id, name, evasion, damage_die, attack_range, attack, stress_max, stress_marked, experiences, upgrades, notes, created_at, updated_at
`

type UpdateCompanionParams struct {
	Name        string
	Evasion     int64
	DamageDie   string
	AttackRange string
	Attack      string
	StressMax   int64
	Experiences string
	Upgrades    string
	Notes       string
	CharacterID int64
}

func (q *Queries) UpdateCompanion(ctx context.Context, arg UpdateCompanionParams) (Companion, error) {
	row := q.db.QueryRowContext(ctx, updateCompanion,
		arg.Name,
		arg.Evasion,
		arg.DamageDie,
		arg.AttackRange,
		arg.Attack,
		arg.StressMax,
		arg.Experiences,
		arg.Upgrades,
		arg.Notes,
		arg.CharacterID,
	)
	var i Companion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Evasion,
		&i.DamageDie,
		&i.AttackRange,
		&i.Attack,
		&i.StressMax,
		&i.StressMarked,
		&i.Experiences,
		&i.Upgrades,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
