// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countdowns.sql

package db

import (
	"context"
	"database/sql"
)

const adjustCountdown = `-- name: AdjustCountdown :one
UPDATE countdowns SET
  value = max(0, min("max", value + ?1)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, value, max, kind, created_at, updated_at, campaign_id
`

type AdjustCountdownParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCountdown(ctx context.Context, arg AdjustCountdownParams) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, adjustCountdown, arg.Delta, arg.ID)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
	)
	return i, err
}

const createCountdown = `-- name: CreateCountdown :one
INSERT INTO countdowns (name, value, max, kind, campaign_id)
VALUES (?,?,?,?,?)
RETURNING id, name, value, max, kind, created_at, updated_at, campaign_id
`

type CreateCountdownParams struct {
	Name       string
	Value      int64
	Max        int64
	Kind       string
	CampaignID sql.NullInt64
}

func (q *Queries) CreateCountdown(ctx context.Context, arg CreateCountdownParams) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, createCountdown,
		arg.Name,
		arg.Value,
		arg.Max,
		arg.Kind,
		arg.CampaignID,
	)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
	)
	return i, err
}

const deleteCountdown = `-- name: DeleteCountdown :exec
DELETE FROM countdowns
WHERE id = ?
`

func (q *Queries) DeleteCountdown(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCountdown, id)
	return err
}

const getCountdown = `-- name: GetCountdown :one
SELECT id, name, value, max, kind, created_at, updated_at, campaign_id FROM countdowns
WHERE id = ?
`

func (q *Queries) GetCountdown(ctx context.Context, id int64) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, getCountdown, id)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
	)
	return i, err
}

const listCountdowns = `-- name: ListCountdowns :many
SELECT id, name, value, max, kind, created_at, updated_at, campaign_id FROM countdowns
ORDER BY created_at ASC
`

func (q *Queries) ListCountdowns(ctx context.Context) ([]Countdown, error) {
	rows, err := q.db.QueryContext(ctx, listCountdowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Countdown
	for rows.Next() {
		var i Countdown
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Max,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountdownsForCampaign = `-- name: ListCountdownsForCampaign :many
SELECT id, name, value, max, kind, created_at, updated_at, campaign_id FROM countdowns
WHERE campaign_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListCountdownsForCampaign(ctx context.Context, campaignID sql.NullInt64) ([]Countdown, error) {
	rows, err := q.db.QueryContext(ctx, listCountdownsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Countdown
	for rows.Next() {
		var i Countdown
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Max,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedCountdowns = `-- name: ListUnassignedCountdowns :many
SELECT id, name, value, max, kind, created_at, updated_at, campaign_id FROM countdowns
WHERE campaign_id IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListUnassignedCountdowns(ctx context.Context) ([]Countdown, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedCountdowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Countdown
	for rows.Next() {
		var i Countdown
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Max,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountdown = `-- name: UpdateCountdown :one
UPDATE countdowns SET
  name = ?1,
  "max" = ?2,
  value = max(0, min(?2, CAST(?3 AS INTEGER))),
  kind = ?4,
  campaign_id = ?5,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?6
RETURNING id, name, value, max, kind, created_at, updated_at, campaign_id
`

type UpdateCountdownParams struct {
	Name       string
	Max        int64
	Value      int64
	Kind       string
	CampaignID sql.NullInt64
	ID         int64
}

func (q *Queries) UpdateCountdown(ctx context.Context, arg UpdateCountdownParams) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, updateCountdown,
		arg.Name,
		arg.Max,
		arg.Value,
		arg.Kind,
		arg.CampaignID,
		arg.ID,
	)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
	)
	return i, err
}
