// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countdowns.sql

package db

import (
	"context"
)

const adjustCountdown = `-- name: AdjustCountdown :one
UPDATE countdowns SET
  value = max(0, min("max", value + ?1)),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, name, value, max, kind, created_at, updated_at
`

type AdjustCountdownParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustCountdown(ctx context.Context, arg AdjustCountdownParams) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, adjustCountdown, arg.Delta, arg.ID)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCountdown = `-- name: CreateCountdown :one
INSERT INTO countdowns (name, value, max, kind)
VALUES (?,?,?,?)
RETURNING id, name, value, max, kind, created_at, updated_at
`

type CreateCountdownParams struct {
	Name  string
	Value int64
	Max   int64
	Kind  string
}

func (q *Queries) CreateCountdown(ctx context.Context, arg CreateCountdownParams) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, createCountdown,
		arg.Name,
		arg.Value,
		arg.Max,
		arg.Kind,
	)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCountdown = `-- name: DeleteCountdown :exec
DELETE FROM countdowns
WHERE id = ?
`

func (q *Queries) DeleteCountdown(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCountdown, id)
	return err
}

const getCountdown = `-- name: GetCountdown :one
SELECT id, name, value, max, kind, created_at, updated_at FROM countdowns
WHERE id = ?
`

func (q *Queries) GetCountdown(ctx context.Context, id int64) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, getCountdown, id)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCountdowns = `-- name: ListCountdowns :many
SELECT id, name, value, max, kind, created_at, updated_at FROM countdowns
ORDER BY created_at ASC
`

func (q *Queries) ListCountdowns(ctx context.Context) ([]Countdown, error) {
	rows, err := q.db.QueryContext(ctx, listCountdowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Countdown
	for rows.Next() {
		var i Countdown
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Max,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountdown = `-- name: UpdateCountdown :one
UPDATE countdowns SET
  name = ?1,
  "max" = ?2,
  value = max(0, min(?2, ?3)),
  kind = ?4,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?5
RETURNING id, name, value, max, kind, created_at, updated_at
`

type UpdateCountdownParams struct {
	Name  string
	Max   int64
	Value interface{}
	Kind  string
	ID    int64
}

func (q *Queries) UpdateCountdown(ctx context.Context, arg UpdateCountdownParams) (Countdown, error) {
	row := q.db.QueryRowContext(ctx, updateCountdown,
		arg.Name,
		arg.Max,
		arg.Value,
		arg.Kind,
		arg.ID,
	)
	var i Countdown
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Max,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
