// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_environments.sql

package db

import (
	"context"
	"strings"
)

const createCustomEnvironment = `-- name: CreateCustomEnvironment :one
INSERT INTO custom_environments (
  slug, name, tier, type, description, impulses, difficulty,
  potential_adversaries, features
)
VALUES (?,?,?,?,?,?,?,?,?)
RETURNING id, slug, name, tier, type, description, impulses, difficulty, potential_adversaries, features, created_at, updated_at
`

type CreateCustomEnvironmentParams struct {
	Slug                 string
	Name                 string
	Tier                 string
	Type                 string
	Description          string
	Impulses             string
	Difficulty           string
	PotentialAdversaries string
	Features             string
}

func (q *Queries) CreateCustomEnvironment(ctx context.Context, arg CreateCustomEnvironmentParams) (CustomEnvironment, error) {
	row := q.db.QueryRowContext(ctx, createCustomEnvironment,
		arg.Slug,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.Description,
		arg.Impulses,
		arg.Difficulty,
		arg.PotentialAdversaries,
		arg.Features,
	)
	var i CustomEnvironment
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.Impulses,
		&i.Difficulty,
		&i.PotentialAdversaries,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomEnvironment = `-- name: DeleteCustomEnvironment :exec
DELETE FROM custom_environments
WHERE slug = ?
`

func (q *Queries) DeleteCustomEnvironment(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomEnvironment, slug)
	return err
}

const getCustomEnvironmentBySlug = `-- name: GetCustomEnvironmentBySlug :one
SELECT id, slug, name, tier, type, description, impulses, difficulty, potential_adversaries, features, created_at, updated_at FROM custom_environments
WHERE slug = ?
`

func (q *Queries) GetCustomEnvironmentBySlug(ctx context.Context, slug string) (CustomEnvironment, error) {
	row := q.db.QueryRowContext(ctx, getCustomEnvironmentBySlug, slug)
	var i CustomEnvironment
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.Impulses,
		&i.Difficulty,
		&i.PotentialAdversaries,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomEnvironmentsByIDs = `-- name: GetCustomEnvironmentsByIDs :many
SELECT id, slug, name, tier, type, description, impulses, difficulty, potential_adversaries, features, created_at, updated_at FROM custom_environments
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetCustomEnvironmentsByIDs(ctx context.Context, ids []int64) ([]CustomEnvironment, error) {
	query := getCustomEnvironmentsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomEnvironment
	for rows.Next() {
		var i CustomEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tier,
			&i.Type,
			&i.Description,
			&i.Impulses,
			&i.Difficulty,
			&i.PotentialAdversaries,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showAllCustomEnvironments = `-- name: ShowAllCustomEnvironments :many
SELECT id, slug, name, tier, type, description, impulses, difficulty, potential_adversaries, features, created_at, updated_at FROM custom_environments
WHERE (tier = ?1 OR ?1 = '')
  AND (type = ?2 OR ?2 = 'All')
ORDER BY name ASC
`

type ShowAllCustomEnvironmentsParams struct {
	Tier string
	Type string
}

func (q *Queries) ShowAllCustomEnvironments(ctx context.Context, arg ShowAllCustomEnvironmentsParams) ([]CustomEnvironment, error) {
	rows, err := q.db.QueryContext(ctx, showAllCustomEnvironments, arg.Tier, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomEnvironment
	for rows.Next() {
		var i CustomEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tier,
			&i.Type,
			&i.Description,
			&i.Impulses,
			&i.Difficulty,
			&i.PotentialAdversaries,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomEnvironment = `-- name: UpdateCustomEnvironment :one
UPDATE custom_environments SET
  name = ?,
  tier = ?,
  type = ?,
  description = ?,
  impulses = ?,
  difficulty = ?,
  potential_adversaries = ?,
  features = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE slug = ?
RETURNING id, slug, name, tier, type, description, impulses, difficulty, potential_adversaries, features, created_at, updated_at
`

type UpdateCustomEnvironmentParams struct {
	Name                 string
	Tier                 string
	Type                 string
	Description          string
	Impulses             string
	Difficulty           string
	PotentialAdversaries string
	Features             string
	Slug                 string
}

func (q *Queries) UpdateCustomEnvironment(ctx context.Context, arg UpdateCustomEnvironmentParams) (CustomEnvironment, error) {
	row := q.db.QueryRowContext(ctx, updateCustomEnvironment,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.Description,
		arg.Impulses,
		arg.Difficulty,
		arg.PotentialAdversaries,
		arg.Features,
		arg.Slug,
	)
	var i CustomEnvironment
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.Impulses,
		&i.Difficulty,
		&i.PotentialAdversaries,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
