// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_loot.sql

package db

import (
	"context"
)

const createCustomLoot = `-- name: CreateCustomLoot :one
INSERT INTO custom_loot (kind, slug, name, rarity, description)
VALUES (?,?,?,?,?)
RETURNING id, kind, slug, name, rarity, description, created_at, updated_at
`

type CreateCustomLootParams struct {
	Kind        string
	Slug        string
	Name        string
	Rarity      string
	Description string
}

func (q *Queries) CreateCustomLoot(ctx context.Context, arg CreateCustomLootParams) (CustomLoot, error) {
	row := q.db.QueryRowContext(ctx, createCustomLoot,
		arg.Kind,
		arg.Slug,
		arg.Name,
		arg.Rarity,
		arg.Description,
	)
	var i CustomLoot
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Rarity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomLoot = `-- name: DeleteCustomLoot :exec
DELETE FROM custom_loot
WHERE kind = ? AND slug = ?
`

type DeleteCustomLootParams struct {
	Kind string
	Slug string
}

func (q *Queries) DeleteCustomLoot(ctx context.Context, arg DeleteCustomLootParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomLoot, arg.Kind, arg.Slug)
	return err
}

const getCustomLootBySlug = `-- name: GetCustomLootBySlug :one
SELECT id, kind, slug, name, rarity, description, created_at, updated_at FROM custom_loot
WHERE kind = ? AND slug = ?
`

type GetCustomLootBySlugParams struct {
	Kind string
	Slug string
}

func (q *Queries) GetCustomLootBySlug(ctx context.Context, arg GetCustomLootBySlugParams) (CustomLoot, error) {
	row := q.db.QueryRowContext(ctx, getCustomLootBySlug, arg.Kind, arg.Slug)
	var i CustomLoot
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Rarity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const showAllCustomLoot = `-- name: ShowAllCustomLoot :many
SELECT id, kind, slug, name, rarity, description, created_at, updated_at FROM custom_loot
WHERE kind = ?1
  AND (rarity = ?2 OR ?2 = '')
ORDER BY name ASC
`

type ShowAllCustomLootParams struct {
	Kind   string
	Rarity string
}

func (q *Queries) ShowAllCustomLoot(ctx context.Context, arg ShowAllCustomLootParams) ([]CustomLoot, error) {
	rows, err := q.db.QueryContext(ctx, showAllCustomLoot, arg.Kind, arg.Rarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomLoot
	for rows.Next() {
		var i CustomLoot
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomLoot = `-- name: UpdateCustomLoot :one
UPDATE custom_loot SET
  name = ?,
  rarity = ?,
  description = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE kind = ? AND slug = ?
RETURNING id, kind, slug, name, rarity, description, created_at, updated_at
`

type UpdateCustomLootParams struct {
	Name        string
	Rarity      string
	Description string
	Kind        string
	Slug        string
}

func (q *Queries) UpdateCustomLoot(ctx context.Context, arg UpdateCustomLootParams) (CustomLoot, error) {
	row := q.db.QueryRowContext(ctx, updateCustomLoot,
		arg.Name,
		arg.Rarity,
		arg.Description,
		arg.Kind,
		arg.Slug,
	)
	var i CustomLoot
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Rarity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
