// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_adversaries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createCustomAdversary = `-- name: CreateCustomAdversary :one
INSERT INTO custom_adversaries (
  slug, name, tier, type, description, horde_number, motives, experiences,
  difficulty, threshold_minor, threshold_major, hp, stress,
  standard_attack, features
)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
RETURNING id, slug, name, tier, type, description, horde_number, motives, experiences, difficulty, threshold_minor, threshold_major, hp, stress, standard_attack, features, created_at, updated_at
`

type CreateCustomAdversaryParams struct {
	Slug           string
	Name           string
	Tier           string
	Type           string
	Description    string
	HordeNumber    string
	Motives        string
	Experiences    string
	Difficulty     string
	ThresholdMinor string
	ThresholdMajor string
	Hp             string
	Stress         string
	StandardAttack sql.NullString
	Features       sql.NullString
}

func (q *Queries) CreateCustomAdversary(ctx context.Context, arg CreateCustomAdversaryParams) (CustomAdversary, error) {
	row := q.db.QueryRowContext(ctx, createCustomAdversary,
		arg.Slug,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.Description,
		arg.HordeNumber,
		arg.Motives,
		arg.Experiences,
		arg.Difficulty,
		arg.ThresholdMinor,
		arg.ThresholdMajor,
		arg.Hp,
		arg.Stress,
		arg.StandardAttack,
		arg.Features,
	)
	var i CustomAdversary
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.HordeNumber,
		&i.Motives,
		&i.Experiences,
		&i.Difficulty,
		&i.ThresholdMinor,
		&i.ThresholdMajor,
		&i.Hp,
		&i.Stress,
		&i.StandardAttack,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomAdversary = `-- name: DeleteCustomAdversary :exec
DELETE FROM custom_adversaries
WHERE slug = ?
`

func (q *Queries) DeleteCustomAdversary(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomAdversary, slug)
	return err
}

const getCustomByIDs = `-- name: GetCustomByIDs :many
SELECT id, slug, name, tier, type, description, horde_number, motives, experiences, difficulty, threshold_minor, threshold_major, hp, stress, standard_attack, features, created_at, updated_at FROM custom_adversaries
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetCustomByIDs(ctx context.Context, ids []int64) ([]CustomAdversary, error) {
	query := getCustomByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomAdversary
	for rows.Next() {
		var i CustomAdversary
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tier,
			&i.Type,
			&i.Description,
			&i.HordeNumber,
			&i.Motives,
			&i.Experiences,
			&i.Difficulty,
			&i.ThresholdMinor,
			&i.ThresholdMajor,
			&i.Hp,
			&i.Stress,
			&i.StandardAttack,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomBySlug = `-- name: GetCustomBySlug :one
SELECT id, slug, name, tier, type, description, horde_number, motives, experiences, difficulty, threshold_minor, threshold_major, hp, stress, standard_attack, features, created_at, updated_at FROM custom_adversaries
WHERE slug = ?
`

func (q *Queries) GetCustomBySlug(ctx context.Context, slug string) (CustomAdversary, error) {
	row := q.db.QueryRowContext(ctx, getCustomBySlug, slug)
	var i CustomAdversary
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.HordeNumber,
		&i.Motives,
		&i.Experiences,
		&i.Difficulty,
		&i.ThresholdMinor,
		&i.ThresholdMajor,
		&i.Hp,
		&i.Stress,
		&i.StandardAttack,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const showAllCustomAdversaries = `-- name: ShowAllCustomAdversaries :many
SELECT id, slug, name, tier, type, description, horde_number, motives, experiences, difficulty, threshold_minor, threshold_major, hp, stress, standard_attack, features, created_at, updated_at FROM custom_adversaries
WHERE (tier = ?1 OR ?1 = '')
  AND (type = ?2 OR ?2 = 'All')
ORDER BY name ASC
`

type ShowAllCustomAdversariesParams struct {
	Tier string
	Type string
}

func (q *Queries) ShowAllCustomAdversaries(ctx context.Context, arg ShowAllCustomAdversariesParams) ([]CustomAdversary, error) {
	rows, err := q.db.QueryContext(ctx, showAllCustomAdversaries, arg.Tier, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomAdversary
	for rows.Next() {
		var i CustomAdversary
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tier,
			&i.Type,
			&i.Description,
			&i.HordeNumber,
			&i.Motives,
			&i.Experiences,
			&i.Difficulty,
			&i.ThresholdMinor,
			&i.ThresholdMajor,
			&i.Hp,
			&i.Stress,
			&i.StandardAttack,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomAdversary = `-- name: UpdateCustomAdversary :one
UPDATE custom_adversaries SET
  name = ?,
  tier = ?,
  type = ?,
  description = ?,
  horde_number = ?,
  motives = ?,
  experiences = ?,
  difficulty = ?,
  threshold_minor = ?,
  threshold_major = ?,
  hp = ?,
  stress = ?,
  standard_attack = ?,
  features = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE slug = ?
RETURNING id, slug, name, tier, type, description, horde_number, motives, experiences, difficulty, threshold_minor, threshold_major, hp, stress, standard_attack, features, created_at, updated_at
`

type UpdateCustomAdversaryParams struct {
	Name           string
	Tier           string
	Type           string
	Description    string
	HordeNumber    string
	Motives        string
	Experiences    string
	Difficulty     string
	ThresholdMinor string
	ThresholdMajor string
	Hp             string
	Stress         string
	StandardAttack sql.NullString
	Features       sql.NullString
	Slug           string
}

func (q *Queries) UpdateCustomAdversary(ctx context.Context, arg UpdateCustomAdversaryParams) (CustomAdversary, error) {
	row := q.db.QueryRowContext(ctx, updateCustomAdversary,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.Description,
		arg.HordeNumber,
		arg.Motives,
		arg.Experiences,
		arg.Difficulty,
		arg.ThresholdMinor,
		arg.ThresholdMajor,
		arg.Hp,
		arg.Stress,
		arg.StandardAttack,
		arg.Features,
		arg.Slug,
	)
	var i CustomAdversary
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.HordeNumber,
		&i.Motives,
		&i.Experiences,
		&i.Difficulty,
		&i.ThresholdMinor,
		&i.ThresholdMajor,
		&i.Hp,
		&i.Stress,
		&i.StandardAttack,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
