// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_armor.sql

package db

import (
	"context"
)

const createCustomArmor = `-- name: CreateCustomArmor :one
INSERT INTO custom_armor (
  slug, name, tier, description, threshold_major, threshold_severe, base_score, feature
)
VALUES (?,?,?,?,?,?,?,?)
RETURNING id, slug, name, tier, description, threshold_major, threshold_severe, base_score, feature, created_at, updated_at
`

type CreateCustomArmorParams struct {
	Slug            string
	Name            string
	Tier            string
	Description     string
	ThresholdMajor  int64
	ThresholdSevere int64
	BaseScore       int64
	Feature         string
}

func (q *Queries) CreateCustomArmor(ctx context.Context, arg CreateCustomArmorParams) (CustomArmor, error) {
	row := q.db.QueryRowContext(ctx, createCustomArmor,
		arg.Slug,
		arg.Name,
		arg.Tier,
		arg.Description,
		arg.ThresholdMajor,
		arg.ThresholdSevere,
		arg.BaseScore,
		arg.Feature,
	)
	var i CustomArmor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Description,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.BaseScore,
		&i.Feature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomArmor = `-- name: DeleteCustomArmor :exec
DELETE FROM custom_armor
WHERE slug = ?
`

func (q *Queries) DeleteCustomArmor(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomArmor, slug)
	return err
}

const getCustomArmorBySlug = `-- name: GetCustomArmorBySlug :one
SELECT id, slug, name, tier, description, threshold_major, threshold_severe, base_score, feature, created_at, updated_at FROM custom_armor
WHERE slug = ?
`

func (q *Queries) GetCustomArmorBySlug(ctx context.Context, slug string) (CustomArmor, error) {
	row := q.db.QueryRowContext(ctx, getCustomArmorBySlug, slug)
	var i CustomArmor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Description,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.BaseScore,
		&i.Feature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const showAllCustomArmor = `-- name: ShowAllCustomArmor :many
SELECT id, slug, name, tier, description, threshold_major, threshold_severe, base_score, feature, created_at, updated_at FROM custom_armor
WHERE (tier = ?1 OR ?1 = '')
ORDER BY name ASC
`

func (q *Queries) ShowAllCustomArmor(ctx context.Context, tier string) ([]CustomArmor, error) {
	rows, err := q.db.QueryContext(ctx, showAllCustomArmor, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomArmor
	for rows.Next() {
		var i CustomArmor
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tier,
			&i.Description,
			&i.ThresholdMajor,
			&i.ThresholdSevere,
			&i.BaseScore,
			&i.Feature,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomArmor = `-- name: UpdateCustomArmor :one
UPDATE custom_armor SET
  name = ?,
  tier = ?,
  description = ?,
  threshold_major = ?,
  threshold_severe = ?,
  base_score = ?,
  feature = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE slug = ?
RETURNING id, slug, name, tier, description, threshold_major, threshold_severe, base_score, feature, created_at, updated_at
`

type UpdateCustomArmorParams struct {
	Name            string
	Tier            string
	Description     string
	ThresholdMajor  int64
	ThresholdSevere int64
	BaseScore       int64
	Feature         string
	Slug            string
}

func (q *Queries) UpdateCustomArmor(ctx context.Context, arg UpdateCustomArmorParams) (CustomArmor, error) {
	row := q.db.QueryRowContext(ctx, updateCustomArmor,
		arg.Name,
		arg.Tier,
		arg.Description,
		arg.ThresholdMajor,
		arg.ThresholdSevere,
		arg.BaseScore,
		arg.Feature,
		arg.Slug,
	)
	var i CustomArmor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Description,
		&i.ThresholdMajor,
		&i.ThresholdSevere,
		&i.BaseScore,
		&i.Feature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
