// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_weapons.sql

package db

import (
	"context"
)

const createCustomWeapon = `-- name: CreateCustomWeapon :one
INSERT INTO custom_weapons (
  slug, name, tier, type, description, category, trait,
  weapon_range, damage, damage_type, burden, feature
)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
RETURNING id, slug, name, tier, type, description, category, trait, weapon_range, damage, damage_type, burden, feature, created_at, updated_at
`

type CreateCustomWeaponParams struct {
	Slug        string
	Name        string
	Tier        string
	Type        string
	Description string
	Category    string
	Trait       string
	WeaponRange string
	Damage      string
	DamageType  string
	Burden      string
	Feature     string
}

func (q *Queries) CreateCustomWeapon(ctx context.Context, arg CreateCustomWeaponParams) (CustomWeapon, error) {
	row := q.db.QueryRowContext(ctx, createCustomWeapon,
		arg.Slug,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.Description,
		arg.Category,
		arg.Trait,
		arg.WeaponRange,
		arg.Damage,
		arg.DamageType,
		arg.Burden,
		arg.Feature,
	)
	var i CustomWeapon
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.Category,
		&i.Trait,
		&i.WeaponRange,
		&i.Damage,
		&i.DamageType,
		&i.Burden,
		&i.Feature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomWeapon = `-- name: DeleteCustomWeapon :exec
DELETE FROM custom_weapons
WHERE slug = ?
`

func (q *Queries) DeleteCustomWeapon(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomWeapon, slug)
	return err
}

const getCustomWeaponBySlug = `-- name: GetCustomWeaponBySlug :one
SELECT id, slug, name, tier, type, description, category, trait, weapon_range, damage, damage_type, burden, feature, created_at, updated_at FROM custom_weapons
WHERE slug = ?
`

func (q *Queries) GetCustomWeaponBySlug(ctx context.Context, slug string) (CustomWeapon, error) {
	row := q.db.QueryRowContext(ctx, getCustomWeaponBySlug, slug)
	var i CustomWeapon
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.Category,
		&i.Trait,
		&i.WeaponRange,
		&i.Damage,
		&i.DamageType,
		&i.Burden,
		&i.Feature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const showAllCustomWeapons = `-- name: ShowAllCustomWeapons :many
SELECT id, slug, name, tier, type, description, category, trait, weapon_range, damage, damage_type, burden, feature, created_at, updated_at FROM custom_weapons
WHERE (tier = ?1 OR ?1 = '')
  AND (type = ?2 OR ?2 = '')
  AND (category = ?3 OR ?3 = '')
ORDER BY name ASC
`

type ShowAllCustomWeaponsParams struct {
	Tier     string
	Type     string
	Category string
}

func (q *Queries) ShowAllCustomWeapons(ctx context.Context, arg ShowAllCustomWeaponsParams) ([]CustomWeapon, error) {
	rows, err := q.db.QueryContext(ctx, showAllCustomWeapons, arg.Tier, arg.Type, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomWeapon
	for rows.Next() {
		var i CustomWeapon
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tier,
			&i.Type,
			&i.Description,
			&i.Category,
			&i.Trait,
			&i.WeaponRange,
			&i.Damage,
			&i.DamageType,
			&i.Burden,
			&i.Feature,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomWeapon = `-- name: UpdateCustomWeapon :one
UPDATE custom_weapons SET
  name = ?,
  tier = ?,
  type = ?,
  description = ?,
  category = ?,
  trait = ?,
  weapon_range = ?,
  damage = ?,
  damage_type = ?,
  burden = ?,
  feature = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE slug = ?
RETURNING id, slug, name, tier, type, description, category, trait, weapon_range, damage, damage_type, burden, feature, created_at, updated_at
`

type UpdateCustomWeaponParams struct {
	Name        string
	Tier        string
	Type        string
	Description string
	Category    string
	Trait       string
	WeaponRange string
	Damage      string
	DamageType  string
	Burden      string
	Feature     string
	Slug        string
}

func (q *Queries) UpdateCustomWeapon(ctx context.Context, arg UpdateCustomWeaponParams) (CustomWeapon, error) {
	row := q.db.QueryRowContext(ctx, updateCustomWeapon,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.Description,
		arg.Category,
		arg.Trait,
		arg.WeaponRange,
		arg.Damage,
		arg.DamageType,
		arg.Burden,
		arg.Feature,
		arg.Slug,
	)
	var i CustomWeapon
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.Description,
		&i.Category,
		&i.Trait,
		&i.WeaponRange,
		&i.Damage,
		&i.DamageType,
		&i.Burden,
		&i.Feature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
