// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encounters.sql

package db

import (
	"context"
	"database/sql"
)

const createEncounter = `-- name: CreateEncounter :one
INSERT INTO encounters (
  encounter_name, adversaries, custom_adversaries, environment_slug, party_id
)
VALUES (?,?,?,?,?)
RETURNING id, encounter_name, adversaries, custom_adversaries, environment_slug, created_at, updated_at, party_id
`

type CreateEncounterParams struct {
	EncounterName     string
	Adversaries       string
	CustomAdversaries string
	EnvironmentSlug   sql.NullString
	PartyID           sql.NullInt64
}

func (q *Queries) CreateEncounter(ctx context.Context, arg CreateEncounterParams) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, createEncounter,
		arg.EncounterName,
		arg.Adversaries,
		arg.CustomAdversaries,
		arg.EnvironmentSlug,
		arg.PartyID,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.EncounterName,
		&i.Adversaries,
		&i.CustomAdversaries,
		&i.EnvironmentSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyID,
	)
	return i, err
}

const deleteEncounter = `-- name: DeleteEncounter :exec
DELETE FROM encounters
WHERE id = ?
`

func (q *Queries) DeleteEncounter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEncounter, id)
	return err
}

const getEncounter = `-- name: GetEncounter :one
SELECT id, encounter_name, adversaries, custom_adversaries, environment_slug, created_at, updated_at, party_id FROM encounters
WHERE id = ?
`

func (q *Queries) GetEncounter(ctx context.Context, id int64) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, getEncounter, id)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.EncounterName,
		&i.Adversaries,
		&i.CustomAdversaries,
		&i.EnvironmentSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyID,
	)
	return i, err
}

const showAllEncounters = `-- name: ShowAllEncounters :many
SELECT id, encounter_name, adversaries, custom_adversaries, environment_slug, created_at, updated_at, party_id FROM encounters
ORDER BY updated_at DESC
`

func (q *Queries) ShowAllEncounters(ctx context.Context) ([]Encounter, error) {
	rows, err := q.db.QueryContext(ctx, showAllEncounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Encounter
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.EncounterName,
			&i.Adversaries,
			&i.CustomAdversaries,
			&i.EnvironmentSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEncounter = `-- name: UpdateEncounter :one
UPDATE encounters SET
  encounter_name = ?,
  adversaries = ?,
  custom_adversaries = ?,
  environment_slug = ?,
  party_id = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, encounter_name, adversaries, custom_adversaries, environment_slug, created_at, updated_at, party_id
`

type UpdateEncounterParams struct {
	EncounterName     string
	Adversaries       string
	CustomAdversaries string
	EnvironmentSlug   sql.NullString
	PartyID           sql.NullInt64
	ID                int64
}

func (q *Queries) UpdateEncounter(ctx context.Context, arg UpdateEncounterParams) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, updateEncounter,
		arg.EncounterName,
		arg.Adversaries,
		arg.CustomAdversaries,
		arg.EnvironmentSlug,
		arg.PartyID,
		arg.ID,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.EncounterName,
		&i.Adversaries,
		&i.CustomAdversaries,
		&i.EnvironmentSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyID,
	)
	return i, err
}
