// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experiences.sql

package db

import (
	"context"
)

const adjustExperienceModifier = `-- name: AdjustExperienceModifier :one
UPDATE experiences SET
  modifier = max(0, min(9, modifier + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, character_id, name, modifier, created_at, updated_at
`

type AdjustExperienceModifierParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustExperienceModifier(ctx context.Context, arg AdjustExperienceModifierParams) (Experience, error) {
	row := q.db.QueryRowContext(ctx, adjustExperienceModifier, arg.Delta, arg.ID)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Modifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExperience = `-- name: CreateExperience :one
INSERT INTO experiences (character_id, name, modifier)
VALUES (?,?,?)
RETURNING id, character_id, name, modifier, created_at, updated_at
`

type CreateExperienceParams struct {
	CharacterID int64
	Name        string
	Modifier    int64
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRowContext(ctx, createExperience, arg.CharacterID, arg.Name, arg.Modifier)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Modifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExperience = `-- name: DeleteExperience :exec
DELETE FROM experiences
WHERE id = ?
`

func (q *Queries) DeleteExperience(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExperience, id)
	return err
}

const getExperience = `-- name: GetExperience :one
SELECT id, character_id, name, modifier, created_at, updated_at FROM experiences
WHERE id = ?
`

func (q *Queries) GetExperience(ctx context.Context, id int64) (Experience, error) {
	row := q.db.QueryRowContext(ctx, getExperience, id)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Modifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExperiences = `-- name: ListExperiences :many
SELECT id, character_id, name, modifier, created_at, updated_at FROM experiences
WHERE character_id = ?
ORDER BY id ASC
`

func (q *Queries) ListExperiences(ctx context.Context, characterID int64) ([]Experience, error) {
	rows, err := q.db.QueryContext(ctx, listExperiences, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Modifier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExperience = `-- name: UpdateExperience :one
UPDATE experiences SET
  name = ?1,
  modifier = ?2,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?3
RETURNING id, character_id, name, modifier, created_at, updated_at
`

type UpdateExperienceParams struct {
	Name     string
	Modifier int64
	ID       int64
}

func (q *Queries) UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error) {
	row := q.db.QueryRowContext(ctx, updateExperience, arg.Name, arg.Modifier, arg.ID)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Modifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
