// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_items.sql

package db

import (
	"context"
)

const adjustInventoryQty = `-- name: AdjustInventoryQty :one
UPDATE inventory_items SET
  qty = max(0, min(999, qty + CAST(?1 AS INTEGER))),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, character_id, name, kind, qty, equipped, detail, created_at, updated_at
`

type AdjustInventoryQtyParams struct {
	Delta int64
	ID    int64
}

func (q *Queries) AdjustInventoryQty(ctx context.Context, arg AdjustInventoryQtyParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, adjustInventoryQty, arg.Delta, arg.ID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Kind,
		&i.Qty,
		&i.Equipped,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (character_id, name, kind, qty, equipped, detail)
VALUES (?,?,?,?,?,?)
RETURNING id, character_id, name, kind, qty, equipped, detail, created_at, updated_at
`

type CreateInventoryItemParams struct {
	CharacterID int64
	Name        string
	Kind        string
	Qty         int64
	Equipped    int64
	Detail      string
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, createInventoryItem,
		arg.CharacterID,
		arg.Name,
		arg.Kind,
		arg.Qty,
		arg.Equipped,
		arg.Detail,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Kind,
		&i.Qty,
		&i.Equipped,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items
WHERE id = ?
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInventoryItem, id)
	return err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, character_id, name, kind, qty, equipped, detail, created_at, updated_at FROM inventory_items
WHERE id = ?
`

func (q *Queries) GetInventoryItem(ctx context.Context, id int64) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, id)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Kind,
		&i.Qty,
		&i.Equipped,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, character_id, name, kind, qty, equipped, detail, created_at, updated_at FROM inventory_items
WHERE character_id = ?
ORDER BY equipped DESC, name ASC
`

func (q *Queries) ListInventoryItems(ctx context.Context, characterID int64) ([]InventoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryItems, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Kind,
			&i.Qty,
			&i.Equipped,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInventoryEquipped = `-- name: SetInventoryEquipped :one
UPDATE inventory_items SET
  equipped = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, character_id, name, kind, qty, equipped, detail, created_at, updated_at
`

type SetInventoryEquippedParams struct {
	Equipped int64
	ID       int64
}

func (q *Queries) SetInventoryEquipped(ctx context.Context, arg SetInventoryEquippedParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, setInventoryEquipped, arg.Equipped, arg.ID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Kind,
		&i.Qty,
		&i.Equipped,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unequipInventoryKind = `-- name: UnequipInventoryKind :exec
UPDATE inventory_items SET
  equipped = 0,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE character_id = ? AND kind = ? AND equipped = 1
`

type UnequipInventoryKindParams struct {
	CharacterID int64
	Kind        string
}

func (q *Queries) UnequipInventoryKind(ctx context.Context, arg UnequipInventoryKindParams) error {
	_, err := q.db.ExecContext(ctx, unequipInventoryKind, arg.CharacterID, arg.Kind)
	return err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory_items SET
  name = ?1,
  kind = ?2,
  qty = ?3,
  equipped = ?4,
  detail = ?5,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?6
RETURNING id, character_id, name, kind, qty, equipped, detail, created_at, updated_at
`

type UpdateInventoryItemParams struct {
	Name     string
	Kind     string
	Qty      int64
	Equipped int64
	Detail   string
	ID       int64
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, updateInventoryItem,
		arg.Name,
		arg.Kind,
		arg.Qty,
		arg.Equipped,
		arg.Detail,
		arg.ID,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Kind,
		&i.Qty,
		&i.Equipped,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
