// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Combat struct {
	ID          int64
	EncounterID sql.NullInt64
	Fear        int64
	Active      int64
	CreatedAt   string
	UpdatedAt   string
}

type Combatant struct {
	ID            int64
	CombatID      int64
	AdversarySlug sql.NullString
	DisplayName   string
	HpMax         int64
	HpMarked      int64
	StressMax     int64
	StressMarked  int64
	Spotlight     int64
	CreatedAt     string
	UpdatedAt     string
}

type Countdown struct {
	ID        int64
	Name      string
	Value     int64
	Max       int64
	Kind      string
	CreatedAt string
	UpdatedAt string
}

type CustomAdversary struct {
	ID             int64
	Slug           string
	Name           string
	Tier           string
	Type           string
	Description    string
	HordeNumber    string
	Motives        string
	Experiences    string
	Difficulty     string
	ThresholdMinor string
	ThresholdMajor string
	Hp             string
	Stress         string
	StandardAttack sql.NullString
	Features       sql.NullString
	CreatedAt      string
	UpdatedAt      string
}

type CustomEnvironment struct {
	ID                   int64
	Slug                 string
	Name                 string
	Tier                 string
	Type                 string
	Description          string
	Impulses             string
	Difficulty           string
	PotentialAdversaries string
	Features             string
	CreatedAt            string
	UpdatedAt            string
}

type Encounter struct {
	ID                int64
	EncounterName     string
	Adversaries       string
	CustomAdversaries string
	EnvironmentSlug   sql.NullString
	CreatedAt         string
	UpdatedAt         string
	PartyID           sql.NullInt64
}

type Party struct {
	ID        int64
	Name      string
	Size      int64
	Tier      string
	CreatedAt string
	UpdatedAt string
}

type Setting struct {
	Key   string
	Value string
}
