// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (campaign_id, kind, title, body)
VALUES (?,?,?,?)
RETURNING id, campaign_id, kind, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	CampaignID int64
	Kind       string
	Title      string
	Body       string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.CampaignID,
		arg.Kind,
		arg.Title,
		arg.Body,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, campaign_id, kind, title, body, created_at, updated_at FROM notes
WHERE id = ?
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesForCampaign = `-- name: ListNotesForCampaign :many
SELECT id, campaign_id, kind, title, body, created_at, updated_at FROM notes
WHERE campaign_id = ?
ORDER BY kind ASC, title ASC
`

func (q *Queries) ListNotesForCampaign(ctx context.Context, campaignID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotesForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesForCampaignByKind = `-- name: ListNotesForCampaignByKind :many
SELECT id, campaign_id, kind, title, body, created_at, updated_at FROM notes
WHERE campaign_id = ? AND kind = ?
ORDER BY title ASC
`

type ListNotesForCampaignByKindParams struct {
	CampaignID int64
	Kind       string
}

func (q *Queries) ListNotesForCampaignByKind(ctx context.Context, arg ListNotesForCampaignByKindParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotesForCampaignByKind, arg.CampaignID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET
  kind = ?,
  title = ?,
  body = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, campaign_id, kind, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	Kind  string
	Title string
	Body  string
	ID    int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
