// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package db

import (
	"context"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (name, size, tier) 
VALUES (?,?,?) 
RETURNING id, name, size, tier, created_at, updated_at
`

type CreatePartyParams struct {
	Name string
	Size int64
	Tier string
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRowContext(ctx, createParty, arg.Name, arg.Size, arg.Tier)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParty = `-- name: DeleteParty :exec
DELETE FROM parties WHERE id = ?
`

func (q *Queries) DeleteParty(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteParty, id)
	return err
}

const getParty = `-- name: GetParty :one
SELECT id, name, size, tier, created_at, updated_at FROM parties 
WHERE id = ?
`

func (q *Queries) GetParty(ctx context.Context, id int64) (Party, error) {
	row := q.db.QueryRowContext(ctx, getParty, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParties = `-- name: ListParties :many
SELECT id, name, size, tier, created_at, updated_at FROM parties 
ORDER BY name ASC
`

func (q *Queries) ListParties(ctx context.Context) ([]Party, error) {
	rows, err := q.db.QueryContext(ctx, listParties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Party
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Tier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParty = `-- name: UpdateParty :one
UPDATE parties SET
  name = ?,
  size = ?,
  tier = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, name, size, tier, created_at, updated_at
`

type UpdatePartyParams struct {
	Name string
	Size int64
	Tier string
	ID   int64
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRowContext(ctx, updateParty,
		arg.Name,
		arg.Size,
		arg.Tier,
		arg.ID,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
