// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
)

const clearCardIndex = `-- name: ClearCardIndex :exec
DELETE FROM search
WHERE entity IN ('adversary', 'environment')
`

func (q *Queries) ClearCardIndex(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCardIndex)
	return err
}

const indexCard = `-- name: IndexCard :exec
INSERT INTO search (entity, entity_id, campaign_id, slug, title, body)
VALUES (?,0,0,?,?,?)
`

type IndexCardParams struct {
	Entity string
	Slug   string
	Title  string
	Body   string
}

func (q *Queries) IndexCard(ctx context.Context, arg IndexCardParams) error {
	_, err := q.db.ExecContext(ctx, indexCard,
		arg.Entity,
		arg.Slug,
		arg.Title,
		arg.Body,
	)
	return err
}
