// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_encounters.sql

package db

import (
	"context"
)

const linkSessionEncounter = `-- name: LinkSessionEncounter :exec
INSERT OR IGNORE INTO session_encounters (session_id, encounter_id)
VALUES (?,?)
`

type LinkSessionEncounterParams struct {
	SessionID   int64
	EncounterID int64
}

func (q *Queries) LinkSessionEncounter(ctx context.Context, arg LinkSessionEncounterParams) error {
	_, err := q.db.ExecContext(ctx, linkSessionEncounter, arg.SessionID, arg.EncounterID)
	return err
}

const listEncountersForSession = `-- name: ListEncountersForSession :many
SELECT encounters.id, encounters.encounter_name, encounters.adversaries, encounters.custom_adversaries, encounters.environment_slug, encounters.created_at, encounters.updated_at, encounters.party_id FROM encounters
JOIN session_encounters ON session_encounters.encounter_id = encounters.id
WHERE session_encounters.session_id = ?
ORDER BY session_encounters.created_at ASC
`

func (q *Queries) ListEncountersForSession(ctx context.Context, sessionID int64) ([]Encounter, error) {
	rows, err := q.db.QueryContext(ctx, listEncountersForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Encounter
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.EncounterName,
			&i.Adversaries,
			&i.CustomAdversaries,
			&i.EnvironmentSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForEncounter = `-- name: ListSessionsForEncounter :many
SELECT sessions.id, sessions.campaign_id, sessions.number, sessions.title, sessions.date, sessions.recap, sessions.created_at, sessions.updated_at FROM sessions
JOIN session_encounters ON session_encounters.session_id = sessions.id
WHERE session_encounters.encounter_id = ?
ORDER BY sessions.number DESC
`

func (q *Queries) ListSessionsForEncounter(ctx context.Context, encounterID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Number,
			&i.Title,
			&i.Date,
			&i.Recap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkSessionEncounter = `-- name: UnlinkSessionEncounter :exec
DELETE FROM session_encounters
WHERE session_id = ? AND encounter_id = ?
`

type UnlinkSessionEncounterParams struct {
	SessionID   int64
	EncounterID int64
}

func (q *Queries) UnlinkSessionEncounter(ctx context.Context, arg UnlinkSessionEncounterParams) error {
	_, err := q.db.ExecContext(ctx, unlinkSessionEncounter, arg.SessionID, arg.EncounterID)
	return err
}
