// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (campaign_id, number, title, date, recap)
VALUES (?,?,?,?,?)
RETURNING id, campaign_id, number, title, date, recap, created_at, updated_at
`

type CreateSessionParams struct {
	CampaignID int64
	Number     int64
	Title      string
	Date       string
	Recap      string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.CampaignID,
		arg.Number,
		arg.Title,
		arg.Date,
		arg.Recap,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Number,
		&i.Title,
		&i.Date,
		&i.Recap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, campaign_id, number, title, date, recap, created_at, updated_at FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Number,
		&i.Title,
		&i.Date,
		&i.Recap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsForCampaign = `-- name: ListSessionsForCampaign :many
SELECT id, campaign_id, number, title, date, recap, created_at, updated_at FROM sessions
WHERE campaign_id = ?
ORDER BY number DESC
`

func (q *Queries) ListSessionsForCampaign(ctx context.Context, campaignID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Number,
			&i.Title,
			&i.Date,
			&i.Recap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSessionNumber = `-- name: NextSessionNumber :one
SELECT coalesce(max(number), 0) + 1 AS next_number FROM sessions
WHERE campaign_id = ?
`

func (q *Queries) NextSessionNumber(ctx context.Context, campaignID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSessionNumber, campaignID)
	var next_number int64
	err := row.Scan(&next_number)
	return next_number, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions SET
  number = ?,
  title = ?,
  date = ?,
  recap = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, campaign_id, number, title, date, recap, created_at, updated_at
`

type UpdateSessionParams struct {
	Number int64
	Title  string
	Date   string
	Recap  string
	ID     int64
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Number,
		arg.Title,
		arg.Date,
		arg.Recap,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Number,
		&i.Title,
		&i.Date,
		&i.Recap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
