// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world_notes.sql

package db

import (
	"context"
	"database/sql"
)

const createWorldNote = `-- name: CreateWorldNote :one
INSERT INTO world_notes (campaign_id, parent_id, kind, title, world_date, body, position)
VALUES (?,?,?,?,?,?,?)
RETURNING id, campaign_id, parent_id, kind, title, world_date, body, position, created_at, updated_at
`

type CreateWorldNoteParams struct {
	CampaignID int64
	ParentID   sql.NullInt64
	Kind       string
	Title      string
	WorldDate  string
	Body       string
	Position   int64
}

func (q *Queries) CreateWorldNote(ctx context.Context, arg CreateWorldNoteParams) (WorldNote, error) {
	row := q.db.QueryRowContext(ctx, createWorldNote,
		arg.CampaignID,
		arg.ParentID,
		arg.Kind,
		arg.Title,
		arg.WorldDate,
		arg.Body,
		arg.Position,
	)
	var i WorldNote
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.WorldDate,
		&i.Body,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorldNote = `-- name: DeleteWorldNote :exec
DELETE FROM world_notes
WHERE id = ?
`

func (q *Queries) DeleteWorldNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorldNote, id)
	return err
}

const getWorldNote = `-- name: GetWorldNote :one
SELECT id, campaign_id, parent_id, kind, title, world_date, body, position, created_at, updated_at FROM world_notes
WHERE id = ?
`

func (q *Queries) GetWorldNote(ctx context.Context, id int64) (WorldNote, error) {
	row := q.db.QueryRowContext(ctx, getWorldNote, id)
	var i WorldNote
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.WorldDate,
		&i.Body,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorldNotesForCampaign = `-- name: ListWorldNotesForCampaign :many
SELECT id, campaign_id, parent_id, kind, title, world_date, body, position, created_at, updated_at FROM world_notes
WHERE campaign_id = ?
ORDER BY position ASC, id ASC
`

func (q *Queries) ListWorldNotesForCampaign(ctx context.Context, campaignID int64) ([]WorldNote, error) {
	rows, err := q.db.QueryContext(ctx, listWorldNotesForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldNote
	for rows.Next() {
		var i WorldNote
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.WorldDate,
			&i.Body,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveWorldNote = `-- name: MoveWorldNote :one
UPDATE world_notes SET
  parent_id = ?,
  position = ?
WHERE id = ?
RETURNING id, campaign_id, parent_id, kind, title, world_date, body, position, created_at, updated_at
`

type MoveWorldNoteParams struct {
	ParentID sql.NullInt64
	Position int64
	ID       int64
}

func (q *Queries) MoveWorldNote(ctx context.Context, arg MoveWorldNoteParams) (WorldNote, error) {
	row := q.db.QueryRowContext(ctx, moveWorldNote, arg.ParentID, arg.Position, arg.ID)
	var i WorldNote
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.WorldDate,
		&i.Body,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextWorldNotePosition = `-- name: NextWorldNotePosition :one
SELECT coalesce(max(position), 0) + 1 AS next_position FROM world_notes
WHERE campaign_id = ?
`

func (q *Queries) NextWorldNotePosition(ctx context.Context, campaignID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextWorldNotePosition, campaignID)
	var next_position int64
	err := row.Scan(&next_position)
	return next_position, err
}

const setWorldNotePosition = `-- name: SetWorldNotePosition :exec
UPDATE world_notes SET
  position = ?
WHERE id = ?
`

type SetWorldNotePositionParams struct {
	Position int64
	ID       int64
}

func (q *Queries) SetWorldNotePosition(ctx context.Context, arg SetWorldNotePositionParams) error {
	_, err := q.db.ExecContext(ctx, setWorldNotePosition, arg.Position, arg.ID)
	return err
}

const updateWorldNote = `-- name: UpdateWorldNote :one
UPDATE world_notes SET
  kind = ?,
  title = ?,
  world_date = ?,
  body = ?,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, campaign_id, parent_id, kind, title, world_date, body, position, created_at, updated_at
`

type UpdateWorldNoteParams struct {
	Kind      string
	Title     string
	WorldDate string
	Body      string
	ID        int64
}

func (q *Queries) UpdateWorldNote(ctx context.Context, arg UpdateWorldNoteParams) (WorldNote, error) {
	row := q.db.QueryRowContext(ctx, updateWorldNote,
		arg.Kind,
		arg.Title,
		arg.WorldDate,
		arg.Body,
		arg.ID,
	)
	var i WorldNote
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.WorldDate,
		&i.Body,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
